# Install/sync backend dependencies
sync-backend:
    uv sync --project backend


# Start backend dev server with hot reload
start:
    uv run --directory backend uvicorn main:app --reload --host 0.0.0.0 --port 8000


# Regenerate Shopify GraphQL client from schema + queries.
# Trims generated/__init__.py to only re-export the public ShopifyClient.
codegen-shopify:
    cd backend/lib/clients/shopify && uv run ariadne-codegen --config ariadne-codegen.toml
    printf '# Generated by ariadne-codegen (slimmed by justfile post-step)\nfrom .client import ShopifyClient\n\n__all__ = ["ShopifyClient"]\n' > backend/lib/clients/shopify/generated/__init__.py


# Deploy a Google Apps Script project (build + push + versioned deploy).
# Usage: just deploy-gas process-refunds-exchanges
#        just deploy-gas process-refunds-exchanges --push-only
deploy-gas project *flags:
    node google-apps-scripts/deploy.js {{project}} {{flags}}
