$schema: http://json-schema.org/draft-07/schema#
title: UpdateValuesByDataFilterResponse
description: The response when updating a range of values by a data filter in a spreadsheet.
type: object
properties:
  dataFilter:
    $ref: DataFilter
    description: The data filter that selected the range that was updated.
  updatedData:
    $ref: ValueRange
    description: The values of the cells in the range matched by the dataFilter after
      all updates were applied. This is only included if the request's `includeValuesInResponse`
      field was `true`.
  updatedRange:
    type: string
    description: The range (in [A1 notation](https://developers.google.com/workspace/sheets/api/guides/concepts#cell))
      that updates were applied to.
  updatedRows:
    type: integer
    description: The number of rows where at least one cell in the row was updated.
    format: int32
  updatedCells:
    description: The number of cells updated.
    format: int32
    type: integer
  updatedColumns:
    description: The number of columns where at least one cell in the column was updated.
    format: int32
    type: integer
