$schema: http://json-schema.org/draft-07/schema#
title: ImapSettings
description: IMAP settings for an account.
type: object
properties:
  enabled:
    description: Whether IMAP is enabled for the account.
    type: boolean
  autoExpunge:
    description: If this value is true, Gmail will immediately expunge a message when
      it is marked as deleted in IMAP. Otherwise, Gmail will wait for an update from
      the client before expunging messages marked as deleted.
    type: boolean
  expungeBehavior:
    description: The action that will be executed on a message when it is marked as
      deleted and expunged from the last visible IMAP folder.
    type: string
    enumDescriptions:
    - Unspecified behavior.
    - Archive messages marked as deleted.
    - Move messages marked as deleted to the trash.
    - Immediately and permanently delete messages marked as deleted. The expunged
      messages cannot be recovered.
    enum:
    - expungeBehaviorUnspecified
    - archive
    - trash
    - deleteForever
  maxFolderSize:
    description: An optional limit on the number of messages that an IMAP folder may
      contain. Legal values are 0, 1000, 2000, 5000 or 10000. A value of zero is interpreted
      to mean that there is no limit.
    type: integer
    format: int32
