# generated by datamodel-codegen:
#   filename:  calendar.yaml
#   timestamp: 2026-03-21T18:41:18+00:00


from datetime import date as date_aliased
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class CalendarApiSchemas(RootModel[Any]):
    root: Annotated[Any, Field(title='Calendar API Schemas')]


class Scope(BaseModel):
    """
    The extent to which calendar access is granted by this ACL rule.
    """

    type: str | None = None
    """
    The type of the scope. Possible values are:
    - "default" - The public scope. This is the default value.
    - "user" - Limits the scope to a single user.
    - "group" - Limits the scope to a group.
    - "domain" - Limits the scope to a domain.  Note: The permissions granted to the "default", or public, scope apply to any user, authenticated or not.
    """
    value: str | None = None
    """
    The email address of a user or group, or the name of a domain, depending on the scope type. Omitted for type "default".
    """


class AclRule(BaseModel):
    etag: str | None = None
    """
    ETag of the resource.
    """
    id: str | None = None
    """
    Identifier of the Access Control List (ACL) rule. See Sharing calendars.
    """
    kind: str | None = 'calendar#aclRule'
    """
    Type of the resource ("calendar#aclRule").
    """
    role: str | None = None
    """
    The role assigned to the scope. Possible values are:
    - "none" - Provides no access.
    - "freeBusyReader" - Provides read access to free/busy information.
    - "reader" - Provides read access to the calendar. Private events will appear to users with reader access, but event details will be hidden.
    - "writer" - Provides read and write access to the calendar. Private events will appear to users with writer access, and event details will be visible. Provides read access to the calendar's ACLs.
    - "owner" - Provides manager access to the calendar. This role has all of the permissions of the writer role with the additional ability to modify access levels of other users.
    Important: the owner role is different from the calendar's data owner. A calendar has a single data owner, but can have multiple users with owner role.
    """
    scope: Scope | None = None
    """
    The extent to which calendar access is granted by this ACL rule.
    """


class CalendarNotification(BaseModel):
    method: str | None = None
    """
    The method used to deliver the notification. The possible value is:
    - "email" - Notifications are sent via email.
    Required when adding a notification.
    """
    type: str | None = None
    """
    The type of notification. Possible values are:
    - "eventCreation" - Notification sent when a new event is put on the calendar.
    - "eventChange" - Notification sent when an event is changed.
    - "eventCancellation" - Notification sent when an event is cancelled.
    - "eventResponse" - Notification sent when an attendee responds to the event invitation.
    - "agenda" - An agenda with the events of the day (sent out in the morning).
    Required when adding a notification.
    """


class Channel(BaseModel):
    address: str | None = None
    """
    The address where notifications are delivered for this channel.
    """
    expiration: str | None = None
    """
    Date and time of notification channel expiration, expressed as a Unix timestamp, in milliseconds. Optional.
    """
    id: str | None = None
    """
    A UUID or similar unique string that identifies this channel.
    """
    kind: str | None = 'api#channel'
    """
    Identifies this as a notification channel used to watch for changes to a resource, which is "api#channel".
    """
    params: dict[str, str] | None = None
    """
    Additional parameters controlling delivery channel behavior. Optional.
    """
    payload: bool | None = None
    """
    A Boolean value to indicate whether payload is wanted. Optional.
    """
    resource_id: Annotated[str | None, Field(alias='resourceId')] = None
    """
    An opaque ID that identifies the resource being watched on this channel. Stable across different API versions.
    """
    resource_uri: Annotated[str | None, Field(alias='resourceUri')] = None
    """
    A version-specific identifier for the watched resource.
    """
    token: str | None = None
    """
    An arbitrary string delivered to the target address with each notification delivered over this channel. Optional.
    """
    type: str | None = None
    """
    The type of delivery mechanism used for this channel. Valid values are "web_hook" (or "webhook"). Both values refer to a channel where Http requests are used to deliver messages.
    """


class ColorDefinition(BaseModel):
    background: str | None = None
    """
    The background color associated with this color definition.
    """
    foreground: str | None = None
    """
    The foreground color that can be used to write on top of a background with 'background' color.
    """


class Colors(BaseModel):
    calendar: dict[str, ColorDefinition] | None = None
    """
    A global palette of calendar colors, mapping from the color ID to its definition. A calendarListEntry resource refers to one of these color IDs in its colorId field. Read-only.
    """
    event: dict[str, ColorDefinition] | None = None
    """
    A global palette of event colors, mapping from the color ID to its definition. An event resource may refer to one of these color IDs in its colorId field. Read-only.
    """
    kind: str | None = 'calendar#colors'
    """
    Type of the resource ("calendar#colors").
    """
    updated: AwareDatetime | None = None
    """
    Last modification time of the color palette (as a RFC3339 timestamp). Read-only.
    """


class Error(BaseModel):
    domain: str | None = None
    """
    Domain, or broad category, of the error.
    """
    reason: str | None = None
    """
    Specific reason for the error. Some of the possible values are:
    - "groupTooBig" - The group of users requested is too large for a single query.
    - "tooManyCalendarsRequested" - The number of calendars requested is too large for a single query.
    - "notFound" - The requested resource was not found.
    - "internalError" - The API service has encountered an internal error.  Additional error types may be added in the future, so clients should gracefully handle additional error statuses not included in this list.
    """


class LabelProperties(BaseModel):
    pass


class ConferenceParametersAddOnParameters(BaseModel):
    parameters: dict[str, str] | None = None


class ConferenceProperties(BaseModel):
    allowed_conference_solution_types: Annotated[
        list[str] | None, Field(alias='allowedConferenceSolutionTypes')
    ] = None
    """
    The types of conference solutions that are supported for this calendar.
    The possible values are:
    - "eventHangout"
    - "eventNamedHangout"
    - "hangoutsMeet"  Optional.
    """


class ConferenceRequestStatus(BaseModel):
    status_code: Annotated[str | None, Field(alias='statusCode')] = None
    """
    The current status of the conference create request. Read-only.
    The possible values are:
    - "pending": the conference create request is still being processed.
    - "success": the conference create request succeeded, the entry points are populated.
    - "failure": the conference create request failed, there are no entry points.
    """


class ConferenceSolutionKey(BaseModel):
    type: str | None = None
    """
    The conference solution type.
    If a client encounters an unfamiliar or empty type, it should still be able to display the entry points. However, it should disallow modifications.
    The possible values are:
    - "eventHangout" for Hangouts for consumers (deprecated; existing events may show this conference solution type but new conferences cannot be created)
    - "eventNamedHangout" for classic Hangouts for Google Workspace users (deprecated; existing events may show this conference solution type but new conferences cannot be created)
    - "hangoutsMeet" for Google Meet (http://meet.google.com)
    - "addOn" for 3P conference providers
    """


class CreateConferenceRequest(BaseModel):
    conference_solution_key: Annotated[
        ConferenceSolutionKey | None, Field(alias='conferenceSolutionKey')
    ] = None
    """
    The conference solution, such as Hangouts or Google Meet.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    The client-generated unique ID for this request.
    Clients should regenerate this ID for every new request. If an ID provided is the same as for the previous request, the request is ignored.
    """
    status: ConferenceRequestStatus | None = None
    """
    The status of the conference create request.
    """


class EntryPoint(BaseModel):
    access_code: Annotated[str | None, Field(alias='accessCode')] = None
    """
    The access code to access the conference. The maximum length is 128 characters.
    When creating new conference data, populate only the subset of {meetingCode, accessCode, passcode, password, pin} fields that match the terminology that the conference provider uses. Only the populated fields should be displayed.
    Optional.
    """
    entry_point_features: Annotated[
        list[str] | None, Field(alias='entryPointFeatures')
    ] = None
    """
    Features of the entry point, such as being toll or toll-free. One entry point can have multiple features. However, toll and toll-free cannot be both set on the same entry point.
    """
    entry_point_type: Annotated[str | None, Field(alias='entryPointType')] = None
    """
    The type of the conference entry point.
    Possible values are:
    - "video" - joining a conference over HTTP. A conference can have zero or one video entry point.
    - "phone" - joining a conference by dialing a phone number. A conference can have zero or more phone entry points.
    - "sip" - joining a conference over SIP. A conference can have zero or one sip entry point.
    - "more" - further conference joining instructions, for example additional phone numbers. A conference can have zero or one more entry point. A conference with only a more entry point is not a valid conference.
    """
    label: str | None = None
    """
    The label for the URI. Visible to end users. Not localized. The maximum length is 512 characters.
    Examples:
    - for video: meet.google.com/aaa-bbbb-ccc
    - for phone: +1 123 268 2601
    - for sip: 12345678@altostrat.com
    - for more: should not be filled
    Optional.
    """
    meeting_code: Annotated[str | None, Field(alias='meetingCode')] = None
    """
    The meeting code to access the conference. The maximum length is 128 characters.
    When creating new conference data, populate only the subset of {meetingCode, accessCode, passcode, password, pin} fields that match the terminology that the conference provider uses. Only the populated fields should be displayed.
    Optional.
    """
    passcode: str | None = None
    """
    The passcode to access the conference. The maximum length is 128 characters.
    When creating new conference data, populate only the subset of {meetingCode, accessCode, passcode, password, pin} fields that match the terminology that the conference provider uses. Only the populated fields should be displayed.
    """
    password: str | None = None
    """
    The password to access the conference. The maximum length is 128 characters.
    When creating new conference data, populate only the subset of {meetingCode, accessCode, passcode, password, pin} fields that match the terminology that the conference provider uses. Only the populated fields should be displayed.
    Optional.
    """
    pin: str | None = None
    """
    The PIN to access the conference. The maximum length is 128 characters.
    When creating new conference data, populate only the subset of {meetingCode, accessCode, passcode, password, pin} fields that match the terminology that the conference provider uses. Only the populated fields should be displayed.
    Optional.
    """
    region_code: Annotated[str | None, Field(alias='regionCode')] = None
    """
    The CLDR/ISO 3166 region code for the country associated with this phone access. Example: "SE" for Sweden.
    Calendar backend will populate this field only for EntryPointType.PHONE.
    """
    uri: str | None = None
    """
    The URI of the entry point. The maximum length is 1300 characters.
    Format:
    - for video, http: or https: schema is required.
    - for phone, tel: schema is required. The URI should include the entire dial sequence (e.g., tel:+12345678900,,,123456789;1234).
    - for sip, sip: schema is required, e.g., sip:12345678@myprovider.com.
    - for more, http: or https: schema is required.
    """


class Creator(BaseModel):
    """
    The creator of the event. Read-only.
    """

    display_name: Annotated[str | None, Field(alias='displayName')] = None
    """
    The creator's name, if available.
    """
    email: str | None = None
    """
    The creator's email address, if available.
    """
    id: str | None = None
    """
    The creator's Profile ID, if available.
    """
    self: bool | None = 'false'
    """
    Whether the creator corresponds to the calendar on which this copy of the event appears. Read-only. The default is False.
    """


class ExtendedProperties(BaseModel):
    """
    Extended properties of the event.
    """

    private: dict[str, str] | None = None
    """
    Properties that are private to the copy of the event that appears on this calendar.
    """
    shared: dict[str, str] | None = None
    """
    Properties that are shared between copies of the event on other attendees' calendars.
    """


class Gadget(BaseModel):
    """
    A gadget that extends this event. Gadgets are deprecated; this structure is instead only used for returning birthday calendar metadata.
    """

    display: str | None = None
    """
    The gadget's display mode. Deprecated. Possible values are:
    - "icon" - The gadget displays next to the event's title in the calendar view.
    - "chip" - The gadget displays when the event is clicked.
    """
    height: int | None = None
    """
    The gadget's height in pixels. The height must be an integer greater than 0. Optional. Deprecated.
    """
    icon_link: Annotated[str | None, Field(alias='iconLink')] = None
    """
    The gadget's icon URL. The URL scheme must be HTTPS. Deprecated.
    """
    link: str | None = None
    """
    The gadget's URL. The URL scheme must be HTTPS. Deprecated.
    """
    preferences: dict[str, str] | None = None
    """
    Preferences.
    """
    title: str | None = None
    """
    The gadget's title. Deprecated.
    """
    type: str | None = None
    """
    The gadget's type. Deprecated.
    """
    width: int | None = None
    """
    The gadget's width in pixels. The width must be an integer greater than 0. Optional. Deprecated.
    """


class Organizer(BaseModel):
    """
    The organizer of the event. If the organizer is also an attendee, this is indicated with a separate entry in attendees with the organizer field set to True. To change the organizer, use the move operation. Read-only, except when importing an event.
    """

    display_name: Annotated[str | None, Field(alias='displayName')] = None
    """
    The organizer's name, if available.
    """
    email: str | None = None
    """
    The organizer's email address, if available. It must be a valid email address as per RFC5322.
    """
    id: str | None = None
    """
    The organizer's Profile ID, if available.
    """
    self: bool | None = 'false'
    """
    Whether the organizer corresponds to the calendar on which this copy of the event appears. Read-only. The default is False.
    """


class Source(BaseModel):
    """
    Source from which the event was created. For example, a web page, an email message or any document identifiable by an URL with HTTP or HTTPS scheme. Can only be seen or modified by the creator of the event.
    """

    title: str | None = None
    """
    Title of the source; for example a title of a web page or an email subject.
    """
    url: str | None = None
    """
    URL of the source pointing to a resource. The URL scheme must be HTTP or HTTPS.
    """


class EventAttachment(BaseModel):
    file_id: Annotated[str | None, Field(alias='fileId')] = None
    """
    ID of the attached file. Read-only.
    For Google Drive files, this is the ID of the corresponding Files resource entry in the Drive API.
    """
    file_url: Annotated[str | None, Field(alias='fileUrl')] = None
    """
    URL link to the attachment.
    For adding Google Drive file attachments use the same format as in alternateLink property of the Files resource in the Drive API.
    Required when adding an attachment.
    """
    icon_link: Annotated[str | None, Field(alias='iconLink')] = None
    """
    URL link to the attachment's icon. This field can only be modified for custom third-party attachments.
    """
    mime_type: Annotated[str | None, Field(alias='mimeType')] = None
    """
    Internet media type (MIME type) of the attachment.
    """
    title: str | None = None
    """
    Attachment title.
    """


class EventAttendee(BaseModel):
    additional_guests: Annotated[int | None, Field(alias='additionalGuests')] = '0'
    """
    Number of additional guests. Optional. The default is 0.
    """
    comment: str | None = None
    """
    The attendee's response comment. Optional.
    """
    display_name: Annotated[str | None, Field(alias='displayName')] = None
    """
    The attendee's name, if available. Optional.
    """
    email: str | None = None
    """
    The attendee's email address, if available. This field must be present when adding an attendee. It must be a valid email address as per RFC5322.
    Required when adding an attendee.
    """
    id: str | None = None
    """
    The attendee's Profile ID, if available.
    """
    optional: bool | None = 'false'
    """
    Whether this is an optional attendee. Optional. The default is False.
    """
    organizer: bool | None = None
    """
    Whether the attendee is the organizer of the event. Read-only. The default is False.
    """
    resource: bool | None = 'false'
    """
    Whether the attendee is a resource. Can only be set when the attendee is added to the event for the first time. Subsequent modifications are ignored. Optional. The default is False.
    """
    response_status: Annotated[str | None, Field(alias='responseStatus')] = None
    """
    The attendee's response status. Possible values are:
    - "needsAction" - The attendee has not responded to the invitation (recommended for new events).
    - "declined" - The attendee has declined the invitation.
    - "tentative" - The attendee has tentatively accepted the invitation.
    - "accepted" - The attendee has accepted the invitation.  Warning: If you add an event using the values declined, tentative, or accepted, attendees with the "Add invitations to my calendar" setting set to "When I respond to invitation in email" or "Only if the sender is known" might have their response reset to needsAction and won't see an event in their calendar unless they change their response in the event invitation email. Furthermore, if more than 200 guests are invited to the event, response status is not propagated to the guests.
    """
    self: bool | None = 'false'
    """
    Whether this entry represents the calendar on which this copy of the event appears. Read-only. The default is False.
    """


class EventBirthdayProperties(BaseModel):
    contact: str | None = None
    """
    Resource name of the contact this birthday event is linked to. This can be used to fetch contact details from People API. Format: "people/c12345". Read-only.
    """
    custom_type_name: Annotated[str | None, Field(alias='customTypeName')] = None
    """
    Custom type label specified for this event. This is populated if birthdayProperties.type is set to "custom". Read-only.
    """
    type: str | None = 'birthday'
    """
    Type of birthday or special event. Possible values are:
    - "anniversary" - An anniversary other than birthday. Always has a contact.
    - "birthday" - A birthday event. This is the default value.
    - "custom" - A special date whose label is further specified in the customTypeName field. Always has a contact.
    - "other" - A special date which does not fall into the other categories, and does not have a custom label. Always has a contact.
    - "self" - Calendar owner's own birthday. Cannot have a contact.  The Calendar API only supports creating events with the type "birthday". The type cannot be changed after the event is created.
    """


class EventDateTime(BaseModel):
    date: date_aliased | None = None
    """
    The date, in the format "yyyy-mm-dd", if this is an all-day event.
    """
    date_time: Annotated[AwareDatetime | None, Field(alias='dateTime')] = None
    """
    The time, as a combined date-time value (formatted according to RFC3339). A time zone offset is required unless a time zone is explicitly specified in timeZone.
    """
    time_zone: Annotated[str | None, Field(alias='timeZone')] = None
    """
    The time zone in which the time is specified. (Formatted as an IANA Time Zone Database name, e.g. "Europe/Zurich".) For recurring events this field is required and specifies the time zone in which the recurrence is expanded. For single events this field is optional and indicates a custom time zone for the event start/end.
    """


class EventFocusTimeProperties(BaseModel):
    auto_decline_mode: Annotated[str | None, Field(alias='autoDeclineMode')] = None
    """
    Whether to decline meeting invitations which overlap Focus Time events. Valid values are declineNone, meaning that no meeting invitations are declined; declineAllConflictingInvitations, meaning that all conflicting meeting invitations that conflict with the event are declined; and declineOnlyNewConflictingInvitations, meaning that only new conflicting meeting invitations which arrive while the Focus Time event is present are to be declined.
    """
    chat_status: Annotated[str | None, Field(alias='chatStatus')] = None
    """
    The status to mark the user in Chat and related products. This can be available or doNotDisturb.
    """
    decline_message: Annotated[str | None, Field(alias='declineMessage')] = None
    """
    Response message to set if an existing event or new invitation is automatically declined by Calendar.
    """


class EventLabel(BaseModel):
    pass


class EventOutOfOfficeProperties(BaseModel):
    auto_decline_mode: Annotated[str | None, Field(alias='autoDeclineMode')] = None
    """
    Whether to decline meeting invitations which overlap Out of office events. Valid values are declineNone, meaning that no meeting invitations are declined; declineAllConflictingInvitations, meaning that all conflicting meeting invitations that conflict with the event are declined; and declineOnlyNewConflictingInvitations, meaning that only new conflicting meeting invitations which arrive while the Out of office event is present are to be declined.
    """
    decline_message: Annotated[str | None, Field(alias='declineMessage')] = None
    """
    Response message to set if an existing event or new invitation is automatically declined by Calendar.
    """


class EventReminder(BaseModel):
    method: str | None = None
    """
    The method used by this reminder. Possible values are:
    - "email" - Reminders are sent via email.
    - "popup" - Reminders are sent via a UI popup.
    Required when adding a reminder.
    """
    minutes: int | None = None
    """
    Number of minutes before the start of the event when the reminder should trigger. Valid values are between 0 and 40320 (4 weeks in minutes).
    Required when adding a reminder.
    """


class CustomLocation(BaseModel):
    """
    If present, specifies that the user is working from a custom location.
    """

    label: str | None = None
    """
    An optional extra label for additional information.
    """


class OfficeLocation(BaseModel):
    """
    If present, specifies that the user is working from an office.
    """

    building_id: Annotated[str | None, Field(alias='buildingId')] = None
    """
    An optional building identifier. This should reference a building ID in the organization's Resources database.
    """
    desk_id: Annotated[str | None, Field(alias='deskId')] = None
    """
    An optional desk identifier.
    """
    floor_id: Annotated[str | None, Field(alias='floorId')] = None
    """
    An optional floor identifier.
    """
    floor_section_id: Annotated[str | None, Field(alias='floorSectionId')] = None
    """
    An optional floor section identifier.
    """
    label: str | None = None
    """
    The office name that's displayed in Calendar Web and Mobile clients. We recommend you reference a building name in the organization's Resources database.
    """


class EventWorkingLocationProperties(BaseModel):
    custom_location: Annotated[CustomLocation | None, Field(alias='customLocation')] = (
        None
    )
    """
    If present, specifies that the user is working from a custom location.
    """
    home_office: Annotated[Any | None, Field(alias='homeOffice')] = None
    """
    If present, specifies that the user is working at home.
    """
    office_location: Annotated[OfficeLocation | None, Field(alias='officeLocation')] = (
        None
    )
    """
    If present, specifies that the user is working from an office.
    """
    type: str | None = None
    """
    Type of the working location. Possible values are:
    - "homeOffice" - The user is working at home.
    - "officeLocation" - The user is working from an office.
    - "customLocation" - The user is working from a custom location.  Any details are specified in a sub-field of the specified name, but this field may be missing if empty. Any other fields are ignored.
    Required when adding working location properties.
    """


class FreeBusyGroup(BaseModel):
    calendars: list[str] | None = None
    """
    List of calendars' identifiers within a group.
    """
    errors: list[Error] | None = None
    """
    Optional error(s) (if computation for the group failed).
    """


class FreeBusyRequestItem(BaseModel):
    id: str | None = None
    """
    The identifier of a calendar or a group.
    """


class TimePeriod(BaseModel):
    end: AwareDatetime | None = None
    """
    The (exclusive) end of the time period.
    """
    start: AwareDatetime | None = None
    """
    The (inclusive) start of the time period.
    """


class Setting(BaseModel):
    etag: str | None = None
    """
    ETag of the resource.
    """
    id: str | None = None
    """
    The id of the user setting.
    """
    kind: str | None = 'calendar#setting'
    """
    Type of the resource ("calendar#setting").
    """
    value: str | None = None
    """
    Value of the user setting. The format of the value depends on the ID of the setting. It must always be a UTF-8 string of length up to 1024 characters.
    """


class Settings(BaseModel):
    etag: str | None = None
    """
    Etag of the collection.
    """
    items: list[Setting] | None = None
    """
    List of user settings.
    """
    kind: str | None = 'calendar#settings'
    """
    Type of the collection ("calendar#settings").
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Token used to access the next page of this result. Omitted if no further results are available, in which case nextSyncToken is provided.
    """
    next_sync_token: Annotated[str | None, Field(alias='nextSyncToken')] = None
    """
    Token used at a later point in time to retrieve only the entries that have changed since this result was returned. Omitted if further results are available, in which case nextPageToken is provided.
    """


class Acl(BaseModel):
    etag: str | None = None
    """
    ETag of the collection.
    """
    items: list[AclRule] | None = None
    """
    List of rules on the access control list.
    """
    kind: str | None = 'calendar#acl'
    """
    Type of the collection ("calendar#acl").
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Token used to access the next page of this result. Omitted if no further results are available, in which case nextSyncToken is provided.
    """
    next_sync_token: Annotated[str | None, Field(alias='nextSyncToken')] = None
    """
    Token used at a later point in time to retrieve only the entries that have changed since this result was returned. Omitted if further results are available, in which case nextPageToken is provided.
    """


class Calendar(BaseModel):
    auto_accept_invitations: Annotated[
        bool | None, Field(alias='autoAcceptInvitations')
    ] = None
    """
    Whether this calendar automatically accepts invitations. Only valid for resource calendars.
    """
    conference_properties: Annotated[
        ConferenceProperties | None, Field(alias='conferenceProperties')
    ] = None
    """
    Conferencing properties for this calendar, for example what types of conferences are allowed.
    """
    data_owner: Annotated[str | None, Field(alias='dataOwner')] = None
    """
    The email of the owner of the calendar. Set only for secondary calendars. Read-only.
    """
    description: str | None = None
    """
    Description of the calendar. Optional.
    """
    etag: str | None = None
    """
    ETag of the resource.
    """
    id: str | None = None
    """
    Identifier of the calendar. To retrieve IDs call the calendarList.list() method.
    """
    kind: str | None = 'calendar#calendar'
    """
    Type of the resource ("calendar#calendar").
    """
    location: str | None = None
    """
    Geographic location of the calendar as free-form text. Optional.
    """
    summary: str | None = None
    """
    Title of the calendar.
    """
    time_zone: Annotated[str | None, Field(alias='timeZone')] = None
    """
    The time zone of the calendar. (Formatted as an IANA Time Zone Database name, e.g. "Europe/Zurich".) Optional.
    """


class NotificationSettings(BaseModel):
    """
    The notifications that the authenticated user is receiving for this calendar.
    """

    notifications: list[CalendarNotification] | None = None
    """
    The list of notifications set for this calendar.
    """


class CalendarListEntry(BaseModel):
    access_role: Annotated[str | None, Field(alias='accessRole')] = None
    """
    The effective access role that the authenticated user has on the calendar. Read-only. Possible values are:
    - "freeBusyReader" - Provides read access to free/busy information.
    - "reader" - Provides read access to the calendar. Private events will appear to users with reader access, but event details will be hidden.
    - "writer" - Provides read and write access to the calendar. Private events will appear to users with writer access, and event details will be visible.
    - "owner" - Provides manager access to the calendar. This role has all of the permissions of the writer role with the additional ability to see and modify access levels of other users.
    Important: the owner role is different from the calendar's data owner. A calendar has a single data owner, but can have multiple users with owner role.
    """
    auto_accept_invitations: Annotated[
        bool | None, Field(alias='autoAcceptInvitations')
    ] = None
    """
    Whether this calendar automatically accepts invitations. Only valid for resource calendars. Read-only.
    """
    background_color: Annotated[str | None, Field(alias='backgroundColor')] = None
    """
    The main color of the calendar in the hexadecimal format "#0088aa". This property supersedes the index-based colorId property. To set or change this property, you need to specify colorRgbFormat=true in the parameters of the insert, update and patch methods. Optional.
    """
    color_id: Annotated[str | None, Field(alias='colorId')] = None
    """
    The color of the calendar. This is an ID referring to an entry in the calendar section of the colors definition (see the colors endpoint). This property is superseded by the backgroundColor and foregroundColor properties and can be ignored when using these properties. Optional.
    """
    conference_properties: Annotated[
        ConferenceProperties | None, Field(alias='conferenceProperties')
    ] = None
    """
    Conferencing properties for this calendar, for example what types of conferences are allowed.
    """
    data_owner: Annotated[str | None, Field(alias='dataOwner')] = None
    """
    The email of the owner of the calendar. Set only for secondary calendars. Read-only.
    """
    default_reminders: Annotated[
        list[EventReminder] | None, Field(alias='defaultReminders')
    ] = None
    """
    The default reminders that the authenticated user has for this calendar.
    """
    deleted: bool | None = 'false'
    """
    Whether this calendar list entry has been deleted from the calendar list. Read-only. Optional. The default is False.
    """
    description: str | None = None
    """
    Description of the calendar. Optional. Read-only.
    """
    etag: str | None = None
    """
    ETag of the resource.
    """
    foreground_color: Annotated[str | None, Field(alias='foregroundColor')] = None
    """
    The foreground color of the calendar in the hexadecimal format "#ffffff". This property supersedes the index-based colorId property. To set or change this property, you need to specify colorRgbFormat=true in the parameters of the insert, update and patch methods. Optional.
    """
    hidden: bool | None = 'false'
    """
    Whether the calendar has been hidden from the list. Optional. The attribute is only returned when the calendar is hidden, in which case the value is true.
    """
    id: str | None = None
    """
    Identifier of the calendar.
    """
    kind: str | None = 'calendar#calendarListEntry'
    """
    Type of the resource ("calendar#calendarListEntry").
    """
    location: str | None = None
    """
    Geographic location of the calendar as free-form text. Optional. Read-only.
    """
    notification_settings: Annotated[
        NotificationSettings | None, Field(alias='notificationSettings')
    ] = None
    """
    The notifications that the authenticated user is receiving for this calendar.
    """
    primary: bool | None = 'false'
    """
    Whether the calendar is the primary calendar of the authenticated user. Read-only. Optional. The default is False.
    """
    selected: bool | None = 'false'
    """
    Whether the calendar content shows up in the calendar UI. Optional. The default is False.
    """
    summary: str | None = None
    """
    Title of the calendar. Read-only.
    """
    summary_override: Annotated[str | None, Field(alias='summaryOverride')] = None
    """
    The summary that the authenticated user has set for this calendar. Optional.
    """
    time_zone: Annotated[str | None, Field(alias='timeZone')] = None
    """
    The time zone of the calendar. Optional. Read-only.
    """


class ConferenceParameters(BaseModel):
    add_on_parameters: Annotated[
        ConferenceParametersAddOnParameters | None, Field(alias='addOnParameters')
    ] = None
    """
    Additional add-on specific data.
    """


class ConferenceSolution(BaseModel):
    icon_uri: Annotated[str | None, Field(alias='iconUri')] = None
    """
    The user-visible icon for this solution.
    """
    key: ConferenceSolutionKey | None = None
    """
    The key which can uniquely identify the conference solution for this event.
    """
    name: str | None = None
    """
    The user-visible name of this solution. Not localized.
    """


class Reminders(BaseModel):
    """
    Information about the event's reminders for the authenticated user. Note that changing reminders does not also change the updated property of the enclosing event.
    """

    overrides: list[EventReminder] | None = None
    """
    If the event doesn't use the default reminders, this lists the reminders specific to the event, or, if not set, indicates that no reminders are set for this event. The maximum number of override reminders is 5.
    """
    use_default: Annotated[bool | None, Field(alias='useDefault')] = None
    """
    Whether the default reminders of the calendar apply to the event.
    """


class FreeBusyCalendar(BaseModel):
    busy: list[TimePeriod] | None = None
    """
    List of time ranges during which this calendar should be regarded as busy.
    """
    errors: list[Error] | None = None
    """
    Optional error(s) (if computation for the calendar failed).
    """


class FreeBusyRequest(BaseModel):
    calendar_expansion_max: Annotated[
        int | None, Field(alias='calendarExpansionMax')
    ] = None
    """
    Maximal number of calendars for which FreeBusy information is to be provided. Optional. Maximum value is 50.
    """
    group_expansion_max: Annotated[int | None, Field(alias='groupExpansionMax')] = None
    """
    Maximal number of calendar identifiers to be provided for a single group. Optional. An error is returned for a group with more members than this value. Maximum value is 100.
    """
    items: list[FreeBusyRequestItem] | None = None
    """
    List of calendars and/or groups to query.
    """
    time_max: Annotated[AwareDatetime | None, Field(alias='timeMax')] = None
    """
    The end of the interval for the query formatted as per RFC3339.
    """
    time_min: Annotated[AwareDatetime | None, Field(alias='timeMin')] = None
    """
    The start of the interval for the query formatted as per RFC3339.
    """
    time_zone: Annotated[str | None, Field(alias='timeZone')] = 'UTC'
    """
    Time zone used in the response. Optional. The default is UTC.
    """


class FreeBusyResponse(BaseModel):
    calendars: dict[str, FreeBusyCalendar] | None = None
    """
    List of free/busy information for calendars.
    """
    groups: dict[str, FreeBusyGroup] | None = None
    """
    Expansion of groups.
    """
    kind: str | None = 'calendar#freeBusy'
    """
    Type of the resource ("calendar#freeBusy").
    """
    time_max: Annotated[AwareDatetime | None, Field(alias='timeMax')] = None
    """
    The end of the interval.
    """
    time_min: Annotated[AwareDatetime | None, Field(alias='timeMin')] = None
    """
    The start of the interval.
    """


class CalendarList(BaseModel):
    etag: str | None = None
    """
    ETag of the collection.
    """
    items: list[CalendarListEntry] | None = None
    """
    Calendars that are present on the user's calendar list.
    """
    kind: str | None = 'calendar#calendarList'
    """
    Type of the collection ("calendar#calendarList").
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Token used to access the next page of this result. Omitted if no further results are available, in which case nextSyncToken is provided.
    """
    next_sync_token: Annotated[str | None, Field(alias='nextSyncToken')] = None
    """
    Token used at a later point in time to retrieve only the entries that have changed since this result was returned. Omitted if further results are available, in which case nextPageToken is provided.
    """


class ConferenceData(BaseModel):
    conference_id: Annotated[str | None, Field(alias='conferenceId')] = None
    """
    The ID of the conference.
    Can be used by developers to keep track of conferences, should not be displayed to users.
    The ID value is formed differently for each conference solution type:
    - eventHangout: ID is not set. (This conference type is deprecated.)
    - eventNamedHangout: ID is the name of the Hangout. (This conference type is deprecated.)
    - hangoutsMeet: ID is the 10-letter meeting code, for example aaa-bbbb-ccc.
    - addOn: ID is defined by the third-party provider.  Optional.
    """
    conference_solution: Annotated[
        ConferenceSolution | None, Field(alias='conferenceSolution')
    ] = None
    """
    The conference solution, such as Google Meet.
    Unset for a conference with a failed create request.
    Either conferenceSolution and at least one entryPoint, or createRequest is required.
    """
    create_request: Annotated[
        CreateConferenceRequest | None, Field(alias='createRequest')
    ] = None
    """
    A request to generate a new conference and attach it to the event. The data is generated asynchronously. To see whether the data is present check the status field.
    Either conferenceSolution and at least one entryPoint, or createRequest is required.
    """
    entry_points: Annotated[list[EntryPoint] | None, Field(alias='entryPoints')] = None
    """
    Information about individual conference entry points, such as URLs or phone numbers.
    All of them must belong to the same conference.
    Either conferenceSolution and at least one entryPoint, or createRequest is required.
    """
    notes: str | None = None
    """
    Additional notes (such as instructions from the domain administrator, legal notices) to display to the user. Can contain HTML. The maximum length is 2048 characters. Optional.
    """
    parameters: ConferenceParameters | None = None
    """
    Additional properties related to a conference. An example would be a solution-specific setting for enabling video streaming.
    """
    signature: str | None = None
    """
    The signature of the conference data.
    Generated on server side.
    Unset for a conference with a failed create request.
    Optional for a conference with a pending create request.
    """


class Event(BaseModel):
    anyone_can_add_self: Annotated[bool | None, Field(alias='anyoneCanAddSelf')] = (
        'false'
    )
    """
    Whether anyone can invite themselves to the event (deprecated). Optional. The default is False.
    """
    attachments: list[EventAttachment] | None = None
    """
    File attachments for the event.
    In order to modify attachments the supportsAttachments request parameter should be set to true.
    There can be at most 25 attachments per event,
    """
    attendees: list[EventAttendee] | None = None
    """
    The attendees of the event. See the Events with attendees guide for more information on scheduling events with other calendar users. Service accounts need to use domain-wide delegation of authority to populate the attendee list.
    """
    attendees_omitted: Annotated[bool | None, Field(alias='attendeesOmitted')] = 'false'
    """
    Whether attendees may have been omitted from the event's representation. When retrieving an event, this may be due to a restriction specified by the maxAttendee query parameter. When updating an event, this can be used to only update the participant's response. Optional. The default is False.
    """
    birthday_properties: Annotated[
        EventBirthdayProperties | None, Field(alias='birthdayProperties')
    ] = None
    """
    Birthday or special event data. Used if eventType is "birthday". Immutable.
    """
    color_id: Annotated[str | None, Field(alias='colorId')] = None
    """
    The color of the event. This is an ID referring to an entry in the event section of the colors definition (see the  colors endpoint). Optional.
    """
    conference_data: Annotated[ConferenceData | None, Field(alias='conferenceData')] = (
        None
    )
    """
    The conference-related information, such as details of a Google Meet conference. To create new conference details use the createRequest field. To persist your changes, remember to set the conferenceDataVersion request parameter to 1 for all event modification requests. Warning: Reusing Google Meet conference data across different events can cause access issues and expose meeting details to unintended users. To help ensure meeting privacy, always generate a unique conference for each event by using the createRequest field.
    """
    created: AwareDatetime | None = None
    """
    Creation time of the event (as a RFC3339 timestamp). Read-only.
    """
    creator: Creator | None = None
    """
    The creator of the event. Read-only.
    """
    description: str | None = None
    """
    Description of the event. Can contain HTML. Optional.
    """
    end: EventDateTime | None = None
    """
    The (exclusive) end time of the event. For a recurring event, this is the end time of the first instance.
    """
    end_time_unspecified: Annotated[bool | None, Field(alias='endTimeUnspecified')] = (
        'false'
    )
    """
    Whether the end time is actually unspecified. An end time is still provided for compatibility reasons, even if this attribute is set to True. The default is False.
    """
    etag: str | None = None
    """
    ETag of the resource.
    """
    event_type: Annotated[str | None, Field(alias='eventType')] = 'default'
    """
    Specific type of the event. This cannot be modified after the event is created. Possible values are:
    - "birthday" - A special all-day event with an annual recurrence.
    - "default" - A regular event or not further specified.
    - "focusTime" - A focus-time event.
    - "fromGmail" - An event from Gmail. This type of event cannot be created.
    - "outOfOffice" - An out-of-office event.
    - "workingLocation" - A working location event.
    """
    extended_properties: Annotated[
        ExtendedProperties | None, Field(alias='extendedProperties')
    ] = None
    """
    Extended properties of the event.
    """
    focus_time_properties: Annotated[
        EventFocusTimeProperties | None, Field(alias='focusTimeProperties')
    ] = None
    """
    Focus Time event data. Used if eventType is focusTime.
    """
    gadget: Gadget | None = None
    """
    A gadget that extends this event. Gadgets are deprecated; this structure is instead only used for returning birthday calendar metadata.
    """
    guests_can_invite_others: Annotated[
        bool | None, Field(alias='guestsCanInviteOthers')
    ] = 'true'
    """
    Whether attendees other than the organizer can invite others to the event. Optional. The default is True.
    """
    guests_can_modify: Annotated[bool | None, Field(alias='guestsCanModify')] = 'false'
    """
    Whether attendees other than the organizer can modify the event. Optional. The default is False.
    """
    guests_can_see_other_guests: Annotated[
        bool | None, Field(alias='guestsCanSeeOtherGuests')
    ] = 'true'
    """
    Whether attendees other than the organizer can see who the event's attendees are. Optional. The default is True.
    """
    hangout_link: Annotated[str | None, Field(alias='hangoutLink')] = None
    """
    An absolute link to the Google Hangout associated with this event. Read-only.
    """
    html_link: Annotated[str | None, Field(alias='htmlLink')] = None
    """
    An absolute link to this event in the Google Calendar Web UI. Read-only.
    """
    i_cal_uid: Annotated[str | None, Field(alias='iCalUID')] = None
    """
    Event unique identifier as defined in RFC5545. It is used to uniquely identify events accross calendaring systems and must be supplied when importing events via the import method.
    Note that the iCalUID and the id are not identical and only one of them should be supplied at event creation time. One difference in their semantics is that in recurring events, all occurrences of one event have different ids while they all share the same iCalUIDs. To retrieve an event using its iCalUID, call the events.list method using the iCalUID parameter. To retrieve an event using its id, call the events.get method.
    """
    id: str | None = None
    """
    Opaque identifier of the event. When creating new single or recurring events, you can specify their IDs. Provided IDs must follow these rules:
    - characters allowed in the ID are those used in base32hex encoding, i.e. lowercase letters a-v and digits 0-9, see section 3.1.2 in RFC2938
    - the length of the ID must be between 5 and 1024 characters
    - the ID must be unique per calendar  Due to the globally distributed nature of the system, we cannot guarantee that ID collisions will be detected at event creation time. To minimize the risk of collisions we recommend using an established UUID algorithm such as one described in RFC4122.
    If you do not specify an ID, it will be automatically generated by the server.
    Note that the icalUID and the id are not identical and only one of them should be supplied at event creation time. One difference in their semantics is that in recurring events, all occurrences of one event have different ids while they all share the same icalUIDs.
    """
    kind: str | None = 'calendar#event'
    """
    Type of the resource ("calendar#event").
    """
    location: str | None = None
    """
    Geographic location of the event as free-form text. Optional.
    """
    locked: bool | None = 'false'
    """
    Whether this is a locked event copy where no changes can be made to the main event fields "summary", "description", "location", "start", "end" or "recurrence". The default is False. Read-Only.
    """
    organizer: Organizer | None = None
    """
    The organizer of the event. If the organizer is also an attendee, this is indicated with a separate entry in attendees with the organizer field set to True. To change the organizer, use the move operation. Read-only, except when importing an event.
    """
    original_start_time: Annotated[
        EventDateTime | None, Field(alias='originalStartTime')
    ] = None
    """
    For an instance of a recurring event, this is the time at which this event would start according to the recurrence data in the recurring event identified by recurringEventId. It uniquely identifies the instance within the recurring event series even if the instance was moved to a different time. Immutable.
    """
    out_of_office_properties: Annotated[
        EventOutOfOfficeProperties | None, Field(alias='outOfOfficeProperties')
    ] = None
    """
    Out of office event data. Used if eventType is outOfOffice.
    """
    private_copy: Annotated[bool | None, Field(alias='privateCopy')] = 'false'
    """
    If set to True, Event propagation is disabled. Note that it is not the same thing as Private event properties. Optional. Immutable. The default is False.
    """
    recurrence: list[str] | None = None
    """
    List of RRULE, EXRULE, RDATE and EXDATE lines for a recurring event, as specified in RFC5545. Note that DTSTART and DTEND lines are not allowed in this field; event start and end times are specified in the start and end fields. This field is omitted for single events or instances of recurring events.
    """
    recurring_event_id: Annotated[str | None, Field(alias='recurringEventId')] = None
    """
    For an instance of a recurring event, this is the id of the recurring event to which this instance belongs. Immutable.
    """
    reminders: Reminders | None = None
    """
    Information about the event's reminders for the authenticated user. Note that changing reminders does not also change the updated property of the enclosing event.
    """
    sequence: int | None = None
    """
    Sequence number as per iCalendar.
    """
    source: Source | None = None
    """
    Source from which the event was created. For example, a web page, an email message or any document identifiable by an URL with HTTP or HTTPS scheme. Can only be seen or modified by the creator of the event.
    """
    start: EventDateTime | None = None
    """
    The (inclusive) start time of the event. For a recurring event, this is the start time of the first instance.
    """
    status: str | None = None
    """
    Status of the event. Optional. Possible values are:
    - "confirmed" - The event is confirmed. This is the default status.
    - "tentative" - The event is tentatively confirmed.
    - "cancelled" - The event is cancelled (deleted). The list method returns cancelled events only on incremental sync (when syncToken or updatedMin are specified) or if the showDeleted flag is set to true. The get method always returns them.
    A cancelled status represents two different states depending on the event type:
    - Cancelled exceptions of an uncancelled recurring event indicate that this instance should no longer be presented to the user. Clients should store these events for the lifetime of the parent recurring event.
    Cancelled exceptions are only guaranteed to have values for the id, recurringEventId and originalStartTime fields populated. The other fields might be empty.
    - All other cancelled events represent deleted events. Clients should remove their locally synced copies. Such cancelled events will eventually disappear, so do not rely on them being available indefinitely.
    Deleted events are only guaranteed to have the id field populated.   On the organizer's calendar, cancelled events continue to expose event details (summary, location, etc.) so that they can be restored (undeleted). Similarly, the events to which the user was invited and that they manually removed continue to provide details. However, incremental sync requests with showDeleted set to false will not return these details.
    If an event changes its organizer (for example via the move operation) and the original organizer is not on the attendee list, it will leave behind a cancelled event where only the id field is guaranteed to be populated.
    """
    summary: str | None = None
    """
    Title of the event.
    """
    transparency: str | None = 'opaque'
    """
    Whether the event blocks time on the calendar. Optional. Possible values are:
    - "opaque" - Default value. The event does block time on the calendar. This is equivalent to setting Show me as to Busy in the Calendar UI.
    - "transparent" - The event does not block time on the calendar. This is equivalent to setting Show me as to Available in the Calendar UI.
    """
    updated: AwareDatetime | None = None
    """
    Last modification time of the main event data (as a RFC3339 timestamp). Updating event reminders will not cause this to change. Read-only.
    """
    visibility: str | None = 'default'
    """
    Visibility of the event. Optional. Possible values are:
    - "default" - Uses the default visibility for events on the calendar. This is the default value.
    - "public" - The event is public and event details are visible to all readers of the calendar.
    - "private" - The event is private and only event attendees may view event details.
    - "confidential" - The event is private. This value is provided for compatibility reasons.
    """
    working_location_properties: Annotated[
        EventWorkingLocationProperties | None, Field(alias='workingLocationProperties')
    ] = None
    """
    Working location event data.
    """


class Events(BaseModel):
    access_role: Annotated[str | None, Field(alias='accessRole')] = None
    """
    The user's access role for this calendar. Read-only. Possible values are:
    - "none" - The user has no access.
    - "freeBusyReader" - The user has read access to free/busy information.
    - "reader" - The user has read access to the calendar. Private events will appear to users with reader access, but event details will be hidden.
    - "writer" - The user has read and write access to the calendar. Private events will appear to users with writer access, and event details will be visible.
    - "owner" - The user has manager access to the calendar. This role has all of the permissions of the writer role with the additional ability to see and modify access levels of other users.
    Important: the owner role is different from the calendar's data owner. A calendar has a single data owner, but can have multiple users with owner role.
    """
    default_reminders: Annotated[
        list[EventReminder] | None, Field(alias='defaultReminders')
    ] = None
    """
    The default reminders on the calendar for the authenticated user. These reminders apply to all events on this calendar that do not explicitly override them (i.e. do not have reminders.useDefault set to True).
    """
    description: str | None = None
    """
    Description of the calendar. Read-only.
    """
    etag: str | None = None
    """
    ETag of the collection.
    """
    items: list[Event] | None = None
    """
    List of events on the calendar.
    """
    kind: str | None = 'calendar#events'
    """
    Type of the collection ("calendar#events").
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Token used to access the next page of this result. Omitted if no further results are available, in which case nextSyncToken is provided.
    """
    next_sync_token: Annotated[str | None, Field(alias='nextSyncToken')] = None
    """
    Token used at a later point in time to retrieve only the entries that have changed since this result was returned. Omitted if further results are available, in which case nextPageToken is provided.
    """
    summary: str | None = None
    """
    Title of the calendar. Read-only.
    """
    time_zone: Annotated[str | None, Field(alias='timeZone')] = None
    """
    The time zone of the calendar. Read-only.
    """
    updated: AwareDatetime | None = None
    """
    Last modification time of the calendar (as a RFC3339 timestamp). Read-only.
    """
