# generated by datamodel-codegen:
#   filename:  gmail.yaml
#   timestamp: 2026-03-21T18:41:06+00:00
#
# EXTRACTED MODELS (moved to focused files):
#   - Message, MessagePart, MessagePartHeader, MessagePartBody, ClassificationLabelValue, ClassificationLabelFieldValue
#     → shared_utilities/clients/google_client_v2/models/message.py
#   - SendAs, SmtpMsa, SecurityMode, VerificationStatus
#     → shared_utilities/clients/google_client_v2/models/send_as.py


from enum import Enum
from typing import Annotated, Any

from pydantic import Base64Str, BaseModel, Field, RootModel

# Import extracted models to maintain backward compatibility
from shared_utilities.clients.google_client_v2.models.message import (
    Message,
    MessagePart,
    MessagePartBody,
    MessagePartHeader,
    ClassificationLabelValue,
    ClassificationLabelFieldValue,
)
from shared_utilities.clients.google_client_v2.models.send_as import (
    SendAs,
    SmtpMsa,
    SecurityMode,
    VerificationStatus as VerificationStatus2,
)


class GmailApiSchemas(RootModel[Any]):
    root: Annotated[Any, Field(title='Gmail API Schemas')]


class EnablementState(Enum):
    """
    Output only. The current state of the key pair.
    """

    state_unspecified = 'stateUnspecified'
    enabled = 'enabled'
    disabled = 'disabled'


class DisableCseKeyPairRequest(BaseModel):
    """
    Requests to turn off a client-side encryption key pair.
    """


class EnableCseKeyPairRequest(BaseModel):
    """
    Requests to turn on a client-side encryption key pair.
    """


class HardwareKeyMetadata(BaseModel):
    """
    Metadata for hardware keys. If [hardware key encryption](https://support.google.com/a/answer/14153163) is set up for the Google Workspace organization, users can optionally store their private key on their smart card and use it to sign and decrypt email messages in Gmail by inserting their smart card into a reader attached to their Windows device.
    """

    description: str | None = None
    """
    Description about the hardware key.
    """


class KaclsKeyMetadata(BaseModel):
    """
    Metadata for private keys managed by an external key access control list service. For details about managing key access, see [Google Workspace CSE API Reference](https://developers.google.com/workspace/cse/reference).
    """

    kacls_uri: Annotated[str | None, Field(alias='kaclsUri')] = None
    """
    The URI of the key access control list service that manages the private key.
    """
    kacls_data: Annotated[str | None, Field(alias='kaclsData')] = None
    """
    Opaque data generated and used by the key access control list service. Maximum size: 8 KiB.
    """


class ObliterateCseKeyPairRequest(BaseModel):
    """
    Request to obliterate a CSE key pair.
    """


class SignAndEncryptKeyPairs(BaseModel):
    """
    The configuration of a CSE identity that uses different key pairs for signing and encryption.
    """

    signing_key_pair_id: Annotated[str | None, Field(alias='signingKeyPairId')] = None
    """
    The ID of the CseKeyPair that signs outgoing mail.
    """
    encryption_key_pair_id: Annotated[
        str | None, Field(alias='encryptionKeyPairId')
    ] = None
    """
    The ID of the CseKeyPair that encrypts signed outgoing mail.
    """


class VerificationStatus(Enum):
    """
    Indicates whether this address has been verified and can act as a delegate for the account. Read-only.
    """

    verification_status_unspecified = 'verificationStatusUnspecified'
    accepted = 'accepted'
    pending = 'pending'
    rejected = 'rejected'
    expired = 'expired'


class Delegate(BaseModel):
    """
    Settings for a delegate. Delegates can read, send, and delete messages, as well as view and add contacts, for the delegator's account. See "Set up mail delegation" for more information about delegates.
    """

    delegate_email: Annotated[str | None, Field(alias='delegateEmail')] = None
    """
    The email address of the delegate.
    """
    verification_status: Annotated[
        VerificationStatus | None, Field(alias='verificationStatus')
    ] = None
    """
    Indicates whether this address has been verified and can act as a delegate for the account. Read-only.
    """


class ListDelegatesResponse(BaseModel):
    """
    Response for the ListDelegates method.
    """

    delegates: list[Delegate] | None = None
    """
    List of the user's delegates (with any verification status). If an account doesn't have delegates, this field doesn't appear.
    """


class FilterAction(BaseModel):
    """
    A set of actions to perform on a message.
    """

    add_label_ids: Annotated[list[str] | None, Field(alias='addLabelIds')] = None
    """
    List of labels to add to the message.
    """
    remove_label_ids: Annotated[list[str] | None, Field(alias='removeLabelIds')] = None
    """
    List of labels to remove from the message.
    """
    forward: str | None = None
    """
    Email address that the message should be forwarded to.
    """


class SizeComparison(Enum):
    """
    How the message size in bytes should be in relation to the size field.
    """

    unspecified = 'unspecified'
    smaller = 'smaller'
    larger = 'larger'


class FilterCriteria(BaseModel):
    """
    Message matching criteria.
    """

    from_: Annotated[str | None, Field(alias='from')] = None
    """
    The sender's display name or email address.
    """
    to: str | None = None
    """
    The recipient's display name or email address. Includes recipients in the "to", "cc", and "bcc" header fields. You can use simply the local part of the email address. For example, "example" and "example@" both match "example@gmail.com". This field is case-insensitive.
    """
    subject: str | None = None
    """
    Case-insensitive phrase found in the message's subject. Trailing and leading whitespace are be trimmed and adjacent spaces are collapsed.
    """
    query: str | None = None
    """
    Only return messages matching the specified query. Supports the same query format as the Gmail search box. For example, `"from:someuser@example.com rfc822msgid: is:unread"`.
    """
    negated_query: Annotated[str | None, Field(alias='negatedQuery')] = None
    """
    Only return messages not matching the specified query. Supports the same query format as the Gmail search box. For example, `"from:someuser@example.com rfc822msgid: is:unread"`.
    """
    has_attachment: Annotated[bool | None, Field(alias='hasAttachment')] = None
    """
    Whether the message has any attachment.
    """
    exclude_chats: Annotated[bool | None, Field(alias='excludeChats')] = None
    """
    Whether the response should exclude chats.
    """
    size: int | None = None
    """
    The size of the entire RFC822 message in bytes, including all headers and attachments.
    """
    size_comparison: Annotated[SizeComparison | None, Field(alias='sizeComparison')] = (
        None
    )
    """
    How the message size in bytes should be in relation to the size field.
    """


class MessageListVisibility(Enum):
    """
    The visibility of messages with this label in the message list in the Gmail web interface.
    """

    show = 'show'
    hide = 'hide'


class LabelListVisibility(Enum):
    """
    The visibility of the label in the label list in the Gmail web interface.
    """

    label_show = 'labelShow'
    label_show_if_unread = 'labelShowIfUnread'
    label_hide = 'labelHide'


class Type(Enum):
    """
    The owner type for the label. User labels are created by the user and can be modified and deleted by the user and can be applied to any message or thread. System labels are internally created and cannot be added, modified, or deleted. System labels may be able to be applied to or removed from messages and threads under some circumstances but this is not guaranteed. For example, users can apply and remove the `INBOX` and `UNREAD` labels from messages and threads, but cannot apply or remove the `DRAFTS` or `SENT` labels from messages or threads.
    """

    system = 'system'
    user = 'user'


class LabelColor(BaseModel):
    text_color: Annotated[str | None, Field(alias='textColor')] = None
    """
    The text color of the label, represented as hex string. This field is required in order to set the color of a label. Only the following predefined set of color values are allowed: \\#000000, #434343, #666666, #999999, #cccccc, #efefef, #f3f3f3, #ffffff, \\#fb4c2f, #ffad47, #fad165, #16a766, #43d692, #4a86e8, #a479e2, #f691b3, \\#f6c5be, #ffe6c7, #fef1d1, #b9e4d0, #c6f3de, #c9daf8, #e4d7f5, #fcdee8, \\#efa093, #ffd6a2, #fce8b3, #89d3b2, #a0eac9, #a4c2f4, #d0bcf1, #fbc8d9, \\#e66550, #ffbc6b, #fcda83, #44b984, #68dfa9, #6d9eeb, #b694e8, #f7a7c0, \\#cc3a21, #eaa041, #f2c960, #149e60, #3dc789, #3c78d8, #8e63ce, #e07798, \\#ac2b16, #cf8933, #d5ae49, #0b804b, #2a9c68, #285bac, #653e9b, #b65775, \\#822111, #a46a21, #aa8831, #076239, #1a764d, #1c4587, #41236d, #83334c \\#464646, #e7e7e7, #0d3472, #b6cff5, #0d3b44, #98d7e4, #3d188e, #e3d7ff, \\#711a36, #fbd3e0, #8a1c0a, #f2b2a8, #7a2e0b, #ffc8af, #7a4706, #ffdeb5, \\#594c05, #fbe983, #684e07, #fdedc1, #0b4f30, #b3efd3, #04502e, #a2dcc1, \\#c2c2c2, #4986e7, #2da2bb, #b99aff, #994a64, #f691b2, #ff7537, #ffad46, \\#662e37, #ebdbde, #cca6ac, #094228, #42d692, #16a765
    """
    background_color: Annotated[str | None, Field(alias='backgroundColor')] = None
    """
    The background color represented as hex string #RRGGBB (ex #000000). This field is required in order to set the color of a label. Only the following predefined set of color values are allowed: \\#000000, #434343, #666666, #999999, #cccccc, #efefef, #f3f3f3, #ffffff, \\#fb4c2f, #ffad47, #fad165, #16a766, #43d692, #4a86e8, #a479e2, #f691b3, \\#f6c5be, #ffe6c7, #fef1d1, #b9e4d0, #c6f3de, #c9daf8, #e4d7f5, #fcdee8, \\#efa093, #ffd6a2, #fce8b3, #89d3b2, #a0eac9, #a4c2f4, #d0bcf1, #fbc8d9, \\#e66550, #ffbc6b, #fcda83, #44b984, #68dfa9, #6d9eeb, #b694e8, #f7a7c0, \\#cc3a21, #eaa041, #f2c960, #149e60, #3dc789, #3c78d8, #8e63ce, #e07798, \\#ac2b16, #cf8933, #d5ae49, #0b804b, #2a9c68, #285bac, #653e9b, #b65775, \\#822111, #a46a21, #aa8831, #076239, #1a764d, #1c4587, #41236d, #83334c \\#464646, #e7e7e7, #0d3472, #b6cff5, #0d3b44, #98d7e4, #3d188e, #e3d7ff, \\#711a36, #fbd3e0, #8a1c0a, #f2b2a8, #7a2e0b, #ffc8af, #7a4706, #ffdeb5, \\#594c05, #fbe983, #684e07, #fdedc1, #0b4f30, #b3efd3, #04502e, #a2dcc1, \\#c2c2c2, #4986e7, #2da2bb, #b99aff, #994a64, #f691b2, #ff7537, #ffad46, \\#662e37, #ebdbde, #cca6ac, #094228, #42d692, #16a765
    """


class BatchDeleteMessagesRequest(BaseModel):
    ids: list[str] | None = None
    """
    The IDs of the messages to delete.
    """


class BatchModifyMessagesRequest(BaseModel):
    ids: list[str] | None = None
    """
    The IDs of the messages to modify. There is a limit of 1000 ids per request.
    """
    add_label_ids: Annotated[list[str] | None, Field(alias='addLabelIds')] = None
    """
    A list of label IDs to add to messages.
    """
    remove_label_ids: Annotated[list[str] | None, Field(alias='removeLabelIds')] = None
    """
    A list of label IDs to remove from messages.
    """


class ModifyMessageRequest(BaseModel):
    add_label_ids: Annotated[list[str] | None, Field(alias='addLabelIds')] = None
    """
    A list of IDs of labels to add to this message. You can add up to 100 labels with each update.
    """
    remove_label_ids: Annotated[list[str] | None, Field(alias='removeLabelIds')] = None
    """
    A list IDs of labels to remove from this message. You can remove up to 100 labels with each update.
    """


class ModifyThreadRequest(BaseModel):
    add_label_ids: Annotated[list[str] | None, Field(alias='addLabelIds')] = None
    """
    A list of IDs of labels to add to this thread. You can add up to 100 labels with each update.
    """
    remove_label_ids: Annotated[list[str] | None, Field(alias='removeLabelIds')] = None
    """
    A list of IDs of labels to remove from this thread. You can remove up to 100 labels with each update.
    """


class Disposition(Enum):
    """
    The state that a message should be left in after it has been forwarded.
    """

    disposition_unspecified = 'dispositionUnspecified'
    leave_in_inbox = 'leaveInInbox'
    archive = 'archive'
    trash = 'trash'
    mark_read = 'markRead'


class AutoForwarding(BaseModel):
    """
    Auto-forwarding settings for an account.
    """

    enabled: bool | None = None
    """
    Whether all incoming mail is automatically forwarded to another address.
    """
    email_address: Annotated[str | None, Field(alias='emailAddress')] = None
    """
    Email address to which all incoming messages are forwarded. This email address must be a verified member of the forwarding addresses.
    """
    disposition: Disposition | None = None
    """
    The state that a message should be left in after it has been forwarded.
    """


class VerificationStatus1(Enum):
    """
    Indicates whether this address has been verified and is usable for forwarding. Read-only.
    """

    verification_status_unspecified = 'verificationStatusUnspecified'
    accepted = 'accepted'
    pending = 'pending'


class ForwardingAddress(BaseModel):
    """
    Settings for a forwarding address.
    """

    forwarding_email: Annotated[str | None, Field(alias='forwardingEmail')] = None
    """
    An email address to which messages can be forwarded.
    """
    verification_status: Annotated[
        VerificationStatus1 | None, Field(alias='verificationStatus')
    ] = None
    """
    Indicates whether this address has been verified and is usable for forwarding. Read-only.
    """


class ExpungeBehavior(Enum):
    """
    The action that will be executed on a message when it is marked as deleted and expunged from the last visible IMAP folder.
    """

    expunge_behavior_unspecified = 'expungeBehaviorUnspecified'
    archive = 'archive'
    trash = 'trash'
    delete_forever = 'deleteForever'


class ImapSettings(BaseModel):
    """
    IMAP settings for an account.
    """

    enabled: bool | None = None
    """
    Whether IMAP is enabled for the account.
    """
    auto_expunge: Annotated[bool | None, Field(alias='autoExpunge')] = None
    """
    If this value is true, Gmail will immediately expunge a message when it is marked as deleted in IMAP. Otherwise, Gmail will wait for an update from the client before expunging messages marked as deleted.
    """
    expunge_behavior: Annotated[
        ExpungeBehavior | None, Field(alias='expungeBehavior')
    ] = None
    """
    The action that will be executed on a message when it is marked as deleted and expunged from the last visible IMAP folder.
    """
    max_folder_size: Annotated[int | None, Field(alias='maxFolderSize')] = None
    """
    An optional limit on the number of messages that an IMAP folder may contain. Legal values are 0, 1000, 2000, 5000 or 10000. A value of zero is interpreted to mean that there is no limit.
    """


class LanguageSettings(BaseModel):
    """
    Language settings for an account. These settings correspond to the "Language settings" feature in the web interface.
    """

    display_language: Annotated[str | None, Field(alias='displayLanguage')] = None
    """
    The language to display Gmail in, formatted as an RFC 3066 Language Tag (for example `en-GB`, `fr` or `ja` for British English, French, or Japanese respectively). The set of languages supported by Gmail evolves over time, so please refer to the "Language" dropdown in the Gmail settings for all available options, as described in the language settings help article. For a table of sample values, see [Manage language settings](https://developers.google.com/workspace/gmail/api/guides/language-settings). Not all Gmail clients can display the same set of languages. In the case that a user's display language is not available for use on a particular client, said client automatically chooses to display in the closest supported variant (or a reasonable default).
    """


class ListForwardingAddressesResponse(BaseModel):
    """
    Response for the ListForwardingAddresses method.
    """

    forwarding_addresses: Annotated[
        list[ForwardingAddress] | None, Field(alias='forwardingAddresses')
    ] = None
    """
    List of addresses that may be used for forwarding.
    """


class AccessWindow(Enum):
    """
    The range of messages which are accessible via POP.
    """

    access_window_unspecified = 'accessWindowUnspecified'
    disabled = 'disabled'
    from_now_on = 'fromNowOn'
    all_mail = 'allMail'


class Disposition1(Enum):
    """
    The action that will be executed on a message after it has been fetched via POP.
    """

    disposition_unspecified = 'dispositionUnspecified'
    leave_in_inbox = 'leaveInInbox'
    archive = 'archive'
    trash = 'trash'
    mark_read = 'markRead'


class PopSettings(BaseModel):
    """
    POP settings for an account.
    """

    access_window: Annotated[AccessWindow | None, Field(alias='accessWindow')] = None
    """
    The range of messages which are accessible via POP.
    """
    disposition: Disposition1 | None = None
    """
    The action that will be executed on a message after it has been fetched via POP.
    """


class Profile(BaseModel):
    """
    Profile for a Gmail user.
    """

    email_address: Annotated[str | None, Field(alias='emailAddress')] = None
    """
    The user's email address.
    """
    messages_total: Annotated[int | None, Field(alias='messagesTotal')] = None
    """
    The total number of messages in the mailbox.
    """
    threads_total: Annotated[int | None, Field(alias='threadsTotal')] = None
    """
    The total number of threads in the mailbox.
    """
    history_id: Annotated[str | None, Field(alias='historyId')] = None
    """
    The ID of the mailbox's current history record.
    """


class VacationSettings(BaseModel):
    """
    Vacation auto-reply settings for an account. These settings correspond to the "Vacation responder" feature in the web interface.
    """

    enable_auto_reply: Annotated[bool | None, Field(alias='enableAutoReply')] = None
    """
    Flag that controls whether Gmail automatically replies to messages.
    """
    response_subject: Annotated[str | None, Field(alias='responseSubject')] = None
    """
    Optional text to prepend to the subject line in vacation responses. In order to enable auto-replies, either the response subject or the response body must be nonempty.
    """
    response_body_plain_text: Annotated[
        str | None, Field(alias='responseBodyPlainText')
    ] = None
    """
    Response body in plain text format. If both `response_body_plain_text` and `response_body_html` are specified, `response_body_html` will be used.
    """
    response_body_html: Annotated[str | None, Field(alias='responseBodyHtml')] = None
    """
    Response body in HTML format. Gmail will sanitize the HTML before storing it. If both `response_body_plain_text` and `response_body_html` are specified, `response_body_html` will be used.
    """
    restrict_to_contacts: Annotated[bool | None, Field(alias='restrictToContacts')] = (
        None
    )
    """
    Flag that determines whether responses are sent to recipients who are not in the user's list of contacts.
    """
    restrict_to_domain: Annotated[bool | None, Field(alias='restrictToDomain')] = None
    """
    Flag that determines whether responses are sent to recipients who are outside of the user's domain. This feature is only available for Google Workspace users.
    """
    start_time: Annotated[str | None, Field(alias='startTime')] = None
    """
    An optional start time for sending auto-replies (epoch ms). When this is specified, Gmail will automatically reply only to messages that it receives after the start time. If both `startTime` and `endTime` are specified, `startTime` must precede `endTime`.
    """
    end_time: Annotated[str | None, Field(alias='endTime')] = None
    """
    An optional end time for sending auto-replies (epoch ms). When this is specified, Gmail will automatically reply only to messages that it receives before the end time. If both `startTime` and `endTime` are specified, `startTime` must precede `endTime`.
    """


class SmimeInfo(BaseModel):
    """
    An S/MIME email config.
    """

    id: str | None = None
    """
    The immutable ID for the SmimeInfo.
    """
    issuer_cn: Annotated[str | None, Field(alias='issuerCn')] = None
    """
    The S/MIME certificate issuer's common name.
    """
    is_default: Annotated[bool | None, Field(alias='isDefault')] = None
    """
    Whether this SmimeInfo is the default one for this user's send-as address.
    """
    expiration: str | None = None
    """
    When the certificate expires (in milliseconds since epoch).
    """
    pem: str | None = None
    """
    PEM formatted X509 concatenated certificate string (standard base64 encoding). Format used for returning key, which includes public key as well as certificate chain (not private key).
    """
    pkcs12: Base64Str | None = None
    """
    PKCS#12 format containing a single private/public key pair and certificate chain. This format is only accepted from client for creating a new SmimeInfo and is never returned, because the private key is not intended to be exported. PKCS#12 may be encrypted, in which case encryptedKeyPassword should be set appropriately.
    """
    encrypted_key_password: Annotated[
        str | None, Field(alias='encryptedKeyPassword')
    ] = None
    """
    Encrypted key password, when key is encrypted.
    """


class LabelFilterAction(Enum):
    """
    Filtering behavior of `labelIds list` specified. This field is deprecated because it caused incorrect behavior in some cases; use `label_filter_behavior` instead.
    """

    include = 'include'
    exclude = 'exclude'


class LabelFilterBehavior(Enum):
    """
    Filtering behavior of `labelIds list` specified. This field replaces `label_filter_action`; if set, `label_filter_action` is ignored.
    """

    include = 'include'
    exclude = 'exclude'


class WatchRequest(BaseModel):
    """
    Set up or update a new push notification watch on this user's mailbox.
    """

    label_ids: Annotated[list[str] | None, Field(alias='labelIds')] = None
    """
    List of label_ids to restrict notifications about. By default, if unspecified, all changes are pushed out. If specified then dictates which labels are required for a push notification to be generated.
    """
    label_filter_action: Annotated[
        LabelFilterAction | None, Field(alias='labelFilterAction', deprecated=True)
    ] = None
    """
    Filtering behavior of `labelIds list` specified. This field is deprecated because it caused incorrect behavior in some cases; use `label_filter_behavior` instead.
    """
    label_filter_behavior: Annotated[
        LabelFilterBehavior | None, Field(alias='labelFilterBehavior')
    ] = None
    """
    Filtering behavior of `labelIds list` specified. This field replaces `label_filter_action`; if set, `label_filter_action` is ignored.
    """
    topic_name: Annotated[str | None, Field(alias='topicName')] = None
    """
    A fully qualified Google Cloud Pub/Sub API topic name to publish the events to. This topic name **must** already exist in Cloud Pub/Sub and you **must** have already granted gmail "publish" permission on it. For example, "projects/my-project-identifier/topics/my-topic-name" (using the Cloud Pub/Sub "v1" topic naming format). Note that the "my-project-identifier" portion must exactly match your Google developer project id (the one executing this watch request).
    """


class WatchResponse(BaseModel):
    """
    Push notification watch response.
    """

    history_id: Annotated[str | None, Field(alias='historyId')] = None
    """
    The ID of the mailbox's current history record.
    """
    expiration: str | None = None
    """
    When Gmail will stop sending notifications for mailbox updates (epoch millis). Call `watch` again before this time to renew the watch.
    """


class CseIdentity(BaseModel):
    """
    The client-side encryption (CSE) configuration for the email address of an authenticated user. Gmail uses CSE configurations to save drafts of client-side encrypted email messages, and to sign and send encrypted email messages. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/auth/gmail.settings.basic` scope. For users managing their own identities and keypairs, requests require [hardware key encryption](https://support.google.com/a/answer/14153163) turned on and configured.
    """

    email_address: Annotated[str | None, Field(alias='emailAddress')] = None
    """
    The email address for the sending identity. The email address must be the primary email address of the authenticated user.
    """
    primary_key_pair_id: Annotated[str | None, Field(alias='primaryKeyPairId')] = None
    """
    If a key pair is associated, the ID of the key pair, CseKeyPair.
    """
    sign_and_encrypt_key_pairs: Annotated[
        SignAndEncryptKeyPairs | None, Field(alias='signAndEncryptKeyPairs')
    ] = None
    """
    The configuration of a CSE identity that uses different key pairs for signing and encryption.
    """


class CsePrivateKeyMetadata(BaseModel):
    """
    Metadata for a private key instance.
    """

    private_key_metadata_id: Annotated[
        str | None, Field(alias='privateKeyMetadataId')
    ] = None
    """
    Output only. The immutable ID for the private key metadata instance.
    """
    kacls_key_metadata: Annotated[
        KaclsKeyMetadata | None, Field(alias='kaclsKeyMetadata')
    ] = None
    """
    Metadata for a private key instance managed by an external key access control list service.
    """
    hardware_key_metadata: Annotated[
        HardwareKeyMetadata | None, Field(alias='hardwareKeyMetadata')
    ] = None
    """
    Metadata for hardware keys.
    """


class ListCseIdentitiesResponse(BaseModel):
    cse_identities: Annotated[
        list[CseIdentity] | None, Field(alias='cseIdentities')
    ] = None
    """
    One page of the list of CSE identities configured for the user.
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Pagination token to be passed to a subsequent ListCseIdentities call in order to retrieve the next page of identities. If this value is not returned or is the empty string, then no further pages remain.
    """


class Filter(BaseModel):
    """
    Resource definition for Gmail filters. Filters apply to specific messages instead of an entire email thread.
    """

    id: str | None = None
    """
    The server assigned ID of the filter.
    """
    criteria: FilterCriteria | None = None
    """
    Matching criteria for the filter.
    """
    action: FilterAction | None = None
    """
    Action that the filter performs.
    """


class ListFiltersResponse(BaseModel):
    """
    Response for the ListFilters method.
    """

    filter: list[Filter] | None = None
    """
    List of a user's filters.
    """


class Label(BaseModel):
    """
    Labels are used to categorize messages and threads within the user's mailbox. The maximum number of labels supported for a user's mailbox is 10,000.
    """

    id: str | None = None
    """
    The immutable ID of the label.
    """
    name: str | None = None
    """
    The display name of the label.
    """
    message_list_visibility: Annotated[
        MessageListVisibility | None, Field(alias='messageListVisibility')
    ] = None
    """
    The visibility of messages with this label in the message list in the Gmail web interface.
    """
    label_list_visibility: Annotated[
        LabelListVisibility | None, Field(alias='labelListVisibility')
    ] = None
    """
    The visibility of the label in the label list in the Gmail web interface.
    """
    type: Type | None = None
    """
    The owner type for the label. User labels are created by the user and can be modified and deleted by the user and can be applied to any message or thread. System labels are internally created and cannot be added, modified, or deleted. System labels may be able to be applied to or removed from messages and threads under some circumstances but this is not guaranteed. For example, users can apply and remove the `INBOX` and `UNREAD` labels from messages and threads, but cannot apply or remove the `DRAFTS` or `SENT` labels from messages or threads.
    """
    messages_total: Annotated[int | None, Field(alias='messagesTotal')] = None
    """
    The total number of messages with the label.
    """
    messages_unread: Annotated[int | None, Field(alias='messagesUnread')] = None
    """
    The number of unread messages with the label.
    """
    threads_total: Annotated[int | None, Field(alias='threadsTotal')] = None
    """
    The total number of threads with the label.
    """
    threads_unread: Annotated[int | None, Field(alias='threadsUnread')] = None
    """
    The number of unread threads with the label.
    """
    color: LabelColor | None = None
    """
    The color to assign to the label. Color is only available for labels that have their `type` set to `user`.
    """


class ListLabelsResponse(BaseModel):
    labels: list[Label] | None = None
    """
    List of labels. Note that each label resource only contains an `id`, `name`, `messageListVisibility`, `labelListVisibility`, and `type`. The [`labels.get`](https://developers.google.com/workspace/gmail/api/v1/reference/users/labels/get) method can fetch additional label details.
    """


class ListSmimeInfoResponse(BaseModel):
    smime_info: Annotated[list[SmimeInfo] | None, Field(alias='smimeInfo')] = None
    """
    List of SmimeInfo.
    """


class CseKeyPair(BaseModel):
    """
    A client-side encryption S/MIME key pair, which is comprised of a public key, its certificate chain, and metadata for its paired private key. Gmail uses the key pair to complete the following tasks: - Sign outgoing client-side encrypted messages. - Save and reopen drafts of client-side encrypted messages. - Save and reopen sent messages. - Decrypt incoming or archived S/MIME messages. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/auth/gmail.settings.basic` scope. For users managing their own identities and keypairs, requests require [hardware key encryption](https://support.google.com/a/answer/14153163) turned on and configured.
    """

    key_pair_id: Annotated[str | None, Field(alias='keyPairId')] = None
    """
    Output only. The immutable ID for the client-side encryption S/MIME key pair.
    """
    pkcs7: str | None = None
    """
    Input only. The public key and its certificate chain. The chain must be in [PKCS#7](https://en.wikipedia.org/wiki/PKCS_7) format and use PEM encoding and ASCII armor.
    """
    pem: str | None = None
    """
    Output only. The public key and its certificate chain, in [PEM](https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail) format.
    """
    subject_email_addresses: Annotated[
        list[str] | None, Field(alias='subjectEmailAddresses')
    ] = None
    """
    Output only. The email address identities that are specified on the leaf certificate.
    """
    enablement_state: Annotated[
        EnablementState | None, Field(alias='enablementState')
    ] = None
    """
    Output only. The current state of the key pair.
    """
    disable_time: Annotated[str | None, Field(alias='disableTime')] = None
    """
    Output only. If a key pair is set to `DISABLED`, the time that the key pair's state changed from `ENABLED` to `DISABLED`. This field is present only when the key pair is in state `DISABLED`.
    """
    private_key_metadata: Annotated[
        list[CsePrivateKeyMetadata] | None, Field(alias='privateKeyMetadata')
    ] = None
    """
    Metadata for instances of this key pair's private key.
    """


class ListCseKeyPairsResponse(BaseModel):
    cse_key_pairs: Annotated[list[CseKeyPair] | None, Field(alias='cseKeyPairs')] = None
    """
    One page of the list of CSE key pairs installed for the user.
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Pagination token to be passed to a subsequent ListCseKeyPairs call in order to retrieve the next page of key pairs. If this value is not returned, then no further pages remain.
    """


class Thread(BaseModel):
    """
    A collection of messages representing a conversation.
    """

    id: str | None = None
    """
    The unique ID of the thread.
    """
    snippet: str | None = None
    """
    A short part of the message text.
    """
    history_id: Annotated[str | None, Field(alias='historyId')] = None
    """
    The ID of the last history record that modified this thread.
    """
    messages: list[Message] | None = None
    """
    The list of messages in the thread.
    """


class ListSendAsResponse(BaseModel):
    """
    Response for the ListSendAs method.
    """

    send_as: Annotated[list[SendAs] | None, Field(alias='sendAs')] = None
    """
    List of send-as aliases.
    """


class Draft(BaseModel):
    """
    A draft email in the user's mailbox.
    """

    id: str | None = None
    """
    The immutable ID of the draft.
    """
    message: Message | None = None
    """
    The message content of the draft.
    """


class ListDraftsResponse(BaseModel):
    drafts: list[Draft] | None = None
    """
    List of drafts. Note that the `Message` property in each `Draft` resource only contains an `id` and a `threadId`. The [`messages.get`](https://developers.google.com/workspace/gmail/api/v1/reference/users/messages/get) method can fetch additional message details.
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Token to retrieve the next page of results in the list.
    """
    result_size_estimate: Annotated[int | None, Field(alias='resultSizeEstimate')] = (
        None
    )
    """
    Estimated total number of results.
    """


class HistoryLabelAdded(BaseModel):
    message: Message | None = None
    label_ids: Annotated[list[str] | None, Field(alias='labelIds')] = None
    """
    Label IDs added to the message.
    """


class HistoryLabelRemoved(BaseModel):
    message: Message | None = None
    label_ids: Annotated[list[str] | None, Field(alias='labelIds')] = None
    """
    Label IDs removed from the message.
    """


class HistoryMessageAdded(BaseModel):
    message: Message | None = None


class HistoryMessageDeleted(BaseModel):
    message: Message | None = None


class ListMessagesResponse(BaseModel):
    messages: list[Message] | None = None
    """
    List of messages. Note that each message resource contains only an `id` and a `threadId`. Additional message details can be fetched using the messages.get method.
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Token to retrieve the next page of results in the list.
    """
    result_size_estimate: Annotated[int | None, Field(alias='resultSizeEstimate')] = (
        None
    )
    """
    Estimated total number of results.
    """


class ListThreadsResponse(BaseModel):
    threads: list[Thread] | None = None
    """
    List of threads. Note that each thread resource does not contain a list of `messages`. The list of `messages` for a given thread can be fetched using the [`threads.get`](https://developers.google.com/workspace/gmail/api/v1/reference/users/threads/get) method.
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Page token to retrieve the next page of results in the list.
    """
    result_size_estimate: Annotated[int | None, Field(alias='resultSizeEstimate')] = (
        None
    )
    """
    Estimated total number of results.
    """


class History(BaseModel):
    """
    A record of a change to the user's mailbox. Each history change may affect multiple messages in multiple ways.
    """

    id: str | None = None
    """
    The mailbox sequence ID.
    """
    messages: list[Message] | None = None
    """
    List of messages changed in this history record. The fields for specific change types, such as `messagesAdded` may duplicate messages in this field. We recommend using the specific change-type fields instead of this.
    """
    messages_added: Annotated[
        list[HistoryMessageAdded] | None, Field(alias='messagesAdded')
    ] = None
    """
    Messages added to the mailbox in this history record.
    """
    messages_deleted: Annotated[
        list[HistoryMessageDeleted] | None, Field(alias='messagesDeleted')
    ] = None
    """
    Messages deleted (not Trashed) from the mailbox in this history record.
    """
    labels_added: Annotated[
        list[HistoryLabelAdded] | None, Field(alias='labelsAdded')
    ] = None
    """
    Labels added to messages in this history record.
    """
    labels_removed: Annotated[
        list[HistoryLabelRemoved] | None, Field(alias='labelsRemoved')
    ] = None
    """
    Labels removed from messages in this history record.
    """


class ListHistoryResponse(BaseModel):
    history: list[History] | None = None
    """
    List of history records. Any `messages` contained in the response will typically only have `id` and `threadId` fields populated.
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Page token to retrieve the next page of results in the list.
    """
    history_id: Annotated[str | None, Field(alias='historyId')] = None
    """
    The ID of the mailbox's current history record.
    """


MessagePart.model_rebuild()
