/** Build-phase: produce the exact `PreparedRequest`s for every row WITHOUT
 *  sending them. The dry-run preview displays these; the real run executes
 *  them. Builders perform only read/auth lookups (product-by-handle, customer
 *  search, token) needed to make the bytes exact.
 *
 *  All UI text generation (dry-run mrkdwn notes, channel-summary bullet copy)
 *  lives in `views/waitlist/`. This file emits structured outcome data only —
 *  see `outcomes.ts` for the discriminated unions.
 */

import type { League } from "../league/types.ts";
import type { EmailMessage } from "../../shared/google/email_message.ts";
import type { PreparedRequest } from "../../shared/http/prepared_request.ts";
import { productPageUrl, shopifyCustomerAdminUrl } from "../../config/store.ts";
import { formatProductHandle } from "../league/format.ts";
import { type CustomerTagPlan, planCustomerTag } from "../../legacy/shopify_client/customer_ops.ts";
import { findProductByHandle } from "../../legacy/shopify_client/product_ops.ts";
import type { createShopifyClient } from "../../legacy/shopify_client/client.ts";
import type { getOrCreateGoogleClient } from "../../shared/google/client.ts";
import { buildSendEmailRequest } from "../../shared/google/gmail.ts";
import { buildWaitlistAdmitEmail } from "./admit_email.ts";
import type { ActionResult } from "./action_result.ts";
import type { EmailOutcome, ShopifyTagOutcome } from "./outcomes.ts";
import { statusText } from "./status_format.ts";
import type { WaitlistEntry } from "./types.ts";

/** Resolved Shopify side of an admit: tag plan + admin link + classified outcome. */
interface AdmitShopifyPlan {
    tagPlan: CustomerTagPlan | null;
    customerAdminUrl?: string;
    outcome: ShopifyTagOutcome;
}

/** Resolved email side of an admit: built request + the message it encodes + outcome. */
interface AdmitEmailPlan {
    emailRequest: PreparedRequest | null;
    emailMessage: EmailMessage | null;
    outcome: EmailOutcome;
}

/** Aggregated per-row plan + initial result. Mutated by `row_execution.ts`
 *  during a real run. Outcome fields are `null` only for paths that skip
 *  planning entirely (type=remove, or no resolved entry). */
export interface RowProcessing {
    rowStr: string;
    type: "admit" | "remove";
    entry?: WaitlistEntry;
    shouldEmail: boolean;
    result: ActionResult;
    tagPlan: CustomerTagPlan | null;
    emailRequest: PreparedRequest | null;
    emailMessage: EmailMessage | null;
    shopifyOutcome: ShopifyTagOutcome | null;
    emailOutcome: EmailOutcome | null;
    /** Dry-run sheet preview: the row write the downstream step would perform. */
    sheetUrl: string;
    insertedStatus: string;
}

function initActionResult(args: {
    rowNumber: number;
    type: "admit" | "remove";
    entry: WaitlistEntry | undefined;
    league: League;
}): ActionResult {
    const { rowNumber, type, entry, league } = args;
    return {
        rowNumber,
        type,
        name: `${entry?.firstName ?? ""} ${entry?.lastName ?? ""}`.trim() || `row ${rowNumber}`,
        firstName: entry?.firstName ?? "",
        email: entry?.emailAddress ?? "",
        phone: entry?.phoneNumber,
        league,
        shopifyOk: true,
        emailOk: true,
        emailed: false,
        productUrl: productPageUrl(formatProductHandle(league)),
    };
}

/** Pure: derive the structured outcome from the resolved tag plan. */
function shopifyOutcomeFromTagPlan(
    tagPlan: CustomerTagPlan,
    waitlistTag: string,
    emailAddress: string,
): ShopifyTagOutcome {
    switch (tagPlan.action) {
        case "noop":
            return { kind: "noop", waitlistTag };
        case "update":
            return {
                kind: "update",
                customerId: tagPlan.existing?.id ?? "",
                finalTags: tagPlan.finalTags,
            };
        default:
            return { kind: "create", emailAddress, waitlistTag };
    }
}

/** Look up the product by handle and plan the customer tag mutation without
 *  sending it. Emits a structured `ShopifyTagOutcome` — UI dry-run text is
 *  generated by `views/waitlist/`. */
async function planAdmitShopifyTag(
    shopify: ReturnType<typeof createShopifyClient>,
    entry: WaitlistEntry,
    league: League,
): Promise<AdmitShopifyPlan> {
    const expectedHandle = formatProductHandle(league);
    const product = await findProductByHandle(shopify, expectedHandle);

    if (!product) {
        return { tagPlan: null, outcome: { kind: "no_product", expectedHandle } };
    }

    const waitlistTag = `${product.handle}-waitlist`;
    const tagPlan = await planCustomerTag(shopify, entry.emailAddress, waitlistTag, {
        firstName: entry.firstName ?? "",
        lastName: entry.lastName ?? "",
        ...(entry.phoneNumber ? { phone: entry.phoneNumber } : {}),
    });

    const customerAdminUrl = tagPlan.existing?.id
        ? shopifyCustomerAdminUrl(tagPlan.existing.id)
        : undefined;
    const outcome = shopifyOutcomeFromTagPlan(tagPlan, waitlistTag, entry.emailAddress);
    return { tagPlan, customerAdminUrl, outcome };
}

/** Build the gmail send request (or signal a skip via the outcome). */
async function planAdmitEmail(
    google: ReturnType<typeof getOrCreateGoogleClient>,
    entry: WaitlistEntry,
    shouldEmail: boolean,
    league: League,
): Promise<AdmitEmailPlan> {
    if (!shouldEmail) {
        return { emailRequest: null, emailMessage: null, outcome: { kind: "skip_unchecked" } };
    }
    if (!entry.emailAddress) {
        return { emailRequest: null, emailMessage: null, outcome: { kind: "skip_no_address" } };
    }
    const emailMessage = buildWaitlistAdmitEmail(
        { firstName: entry.firstName, emailAddress: entry.emailAddress },
        league,
    );
    const emailRequest = await buildSendEmailRequest(google, emailMessage);
    return { emailRequest, emailMessage, outcome: { kind: "send" } };
}

/** Compose a full `RowProcessing` from the row's selection + the sheet entry.
 *  Orchestrator only — actual planning lives in `planAdmitShopifyTag` and
 *  `planAdmitEmail`. Removes skip planning entirely; the sheet step downstream
 *  is the only side effect a remove produces. */
export async function buildRowProcessing(args: {
    rowStr: string;
    type: "admit" | "remove";
    entry?: WaitlistEntry;
    shouldEmail: boolean;
    shopify: ReturnType<typeof createShopifyClient>;
    google: ReturnType<typeof getOrCreateGoogleClient>;
    /** Used for display only when the row can't be resolved to a sheet entry. */
    fallbackLeague: League;
    timestamp: string;
    sheetUrl: string;
}): Promise<RowProcessing> {
    const { rowStr, type, entry, shouldEmail, shopify, google, fallbackLeague } = args;
    const rowNumber = Number(rowStr);
    // Entry already carries its full League (populated by sheet_parser); fall back
    // to the modal-selected league only when the row no longer resolves to an entry.
    const league: League = entry?.league ?? fallbackLeague;
    const result = initActionResult({ rowNumber, type, entry, league });

    if (!entry || type !== "admit") {
        return {
            rowStr,
            type,
            entry,
            shouldEmail,
            result,
            tagPlan: null,
            emailRequest: null,
            emailMessage: null,
            shopifyOutcome: null,
            emailOutcome: null,
            sheetUrl: args.sheetUrl,
            insertedStatus: statusText(type, args.timestamp),
        };
    }

    const shopifyPlan = await planAdmitShopifyTag(shopify, entry, league);
    if (shopifyPlan.customerAdminUrl) result.customerAdminUrl = shopifyPlan.customerAdminUrl;
    const emailPlan = await planAdmitEmail(google, entry, shouldEmail, league);

    return {
        rowStr,
        type,
        entry,
        shouldEmail,
        result,
        tagPlan: shopifyPlan.tagPlan,
        emailRequest: emailPlan.emailRequest,
        emailMessage: emailPlan.emailMessage,
        shopifyOutcome: shopifyPlan.outcome,
        emailOutcome: emailPlan.outcome,
        sheetUrl: args.sheetUrl,
        insertedStatus: statusText(type, args.timestamp),
    };
}
