"""
Shared signature verification utilities for webhook security.
Supports different signature formats used by various services.
"""

import hmac
import base64
from enum import Enum


class SignatureFormat(Enum):
    """Supported signature formats"""
    BASE64 = "base64"           # Shopify: base64(hmac_digest)
    HEX_WITH_PREFIX = "hex_v0"  # Slack: v0=hex_digest
    HEX = "hex"                 # Plain hex digest


def verify_hmac_signature(
    expected_signature: str,
    received_signature: str,
    signature_format: SignatureFormat,
) -> bool:
    """
    Generic signature comparison supporting multiple formats.
    
    Args:
        expected_signature: The expected signature (generated by service)
        received_signature: The signature to verify
        signature_format: How the signature is encoded
        
    Returns:
        True if signature is valid, False otherwise
    """
    try:
        # Format signatures for secure comparison based on service requirements
        if signature_format == SignatureFormat.BASE64:
            # Both should be base64 strings, decode for binary comparison
            expected_bytes = base64.b64decode(expected_signature)
            received_bytes = base64.b64decode(received_signature)
            return hmac.compare_digest(expected_bytes, received_bytes)
            
        elif signature_format == SignatureFormat.HEX_WITH_PREFIX:
            # Both should be "v0=hex" format, compare as strings
            return hmac.compare_digest(expected_signature, received_signature)
            
        elif signature_format == SignatureFormat.HEX:
            # Both should be hex strings, compare as strings
            return hmac.compare_digest(expected_signature, received_signature)
            
        else:
            raise ValueError(f"Unsupported signature format: {signature_format}")
        
        
    except Exception:
        return False

