"""Public Shopify GraphQL client.

Re-exports the codegen-generated ``ShopifyClient`` as the canonical
import path. The class itself is auto-generated by ariadne-codegen
(see queries/*.graphql + ariadne-codegen.toml). Transport, pagination,
and construction live on its base class in ``client_base.py``.

Usage:
    from lib.clients.shopify.shopify_client import ShopifyClient
    # or simply:
    from lib.clients.shopify import ShopifyClient

    async with ShopifyClient(store_id=..., api_version=..., token=...) as c:
        result = await c.orders_get(query="id:12345", first=1)
        async for o in c.paginate(c.orders_get, "orders", query="product_id:..."):
            ...
"""

from .generated.client import ShopifyClient

__all__ = ["ShopifyClient"]
