/**
 * Generic Google Apps Script esbuild bundler
 * Reads configuration from esbuild.config.js in the project directory
 */

const fs = require('fs');
const path = require('path');

// Resolve esbuild from the project directory (where node_modules is)
// Not from this script's directory
let esbuild;
try {
  esbuild = require(path.join(process.cwd(), 'node_modules', 'esbuild'));
} catch (err) {
  console.error('❌ Error: esbuild not found in project node_modules');
  console.error('   Run: pnpm install (or npm install) in your project directory');
  process.exit(1);
}

// Try to load project-specific config
let config;
try {
  config = require(path.join(process.cwd(), 'esbuild.config.js'));
} catch (err) {
  console.error('❌ Error: No esbuild.config.js found in current directory');
  console.error('   Create an esbuild.config.js file with your project configuration');
  process.exit(1);
}

// Defaults with config overrides
const BUILD_DIR = config.buildDir || 'build';
const SRC_DIR = config.srcDir || 'src';
const OUTPUT_FILE = config.outputFile || 'Code.js';
const ENTRY_POINTS = config.entryPoints || ['src/index.js'];
const TARGET = config.target || 'es2020';
const KEEP_NAMES = config.keepNames !== false; // Default true
const MINIFY = config.minify || false;

async function build() {
  console.log('🏗️  Starting esbuild for Google Apps Script...\n');
  console.log(`📋 Configuration:`);
  console.log(`   Entry points: ${ENTRY_POINTS.join(', ')}`);
  console.log(`   Output: ${BUILD_DIR}/${OUTPUT_FILE}`);
  console.log(`   Target: ${TARGET}\n`);

  // Clean build directory
  if (fs.existsSync(BUILD_DIR)) {
    console.log('🧹 Cleaning build directory...');
    fs.rmSync(BUILD_DIR, { recursive: true });
  }
  fs.mkdirSync(BUILD_DIR, { recursive: true });

  // Build the unified entry point
  for (const entry of ENTRY_POINTS) {
    const relativePath = entry.replace(`${SRC_DIR}/`, '');
    const outputPath = path.join(BUILD_DIR, OUTPUT_FILE);
    
    console.log(`📦 Bundling: ${relativePath} → ${OUTPUT_FILE}`);

    try {
      // Build to a temp file first
      const tempOutput = outputPath + '.tmp';
      
      await esbuild.build({
        entryPoints: [entry],
        bundle: true,
        format: 'esm', // Use ESM format, we'll strip exports later
        platform: 'browser',
        target: TARGET,
        outfile: tempOutput,
        
        // Keep function names for GAS triggers/callbacks
        keepNames: KEEP_NAMES,
        
        // Minify option (usually false for GAS debugging)
        minify: MINIFY,
        
        // Disable tree shaking to preserve trigger functions
        treeShaking: false,
      });
      
      // Read the bundled output
      let code = fs.readFileSync(tempOutput, 'utf-8');
      
      // Remove all import/export statements to make it GAS-compatible
      code = code.replace(/^import .+ from .+;?\s*$/gm, '');
      code = code.replace(/^export \{[^}]+\};?\s*$/gm, '');
      code = code.replace(/^export (default |const |let |var |function |class )/gm, '$1');
      
      // Add banner
      const banner = `/**
 * Auto-generated by esbuild - DO NOT EDIT DIRECTLY
 * Source: ${relativePath}
 * Build time: ${new Date().toISOString()}
 */

`;
      
      code = banner + code;
      
      // Write final output
      const outputDir = path.dirname(outputPath);
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }
      fs.writeFileSync(outputPath, code);
      
      // Clean up temp file
      fs.unlinkSync(tempOutput);
      
      console.log(`   ✅ Success\n`);
      
    } catch (error) {
      console.error(`   ❌ Failed to bundle ${entry}:`);
      console.error(error);
      process.exit(1);
    }
  }

  // Copy appsscript.json
  const appsscriptSource = path.join(SRC_DIR, 'appsscript.json');
  const appsscriptDest = path.join(BUILD_DIR, 'appsscript.json');
  
  if (fs.existsSync(appsscriptSource)) {
    console.log('📋 Copying appsscript.json...');
    fs.copyFileSync(appsscriptSource, appsscriptDest);
    console.log('   ✅ Success\n');
  } else {
    console.warn('⚠️  Warning: appsscript.json not found in src/\n');
  }

  // Summary
  console.log('✨ Build complete!\n');
  console.log(`📂 Output: ${BUILD_DIR}/${OUTPUT_FILE}`);
  console.log(`📦 Unified bundle with all trigger functions`);
  console.log(`✅ No duplicate function definitions`);
  console.log('\nNext steps:');
  console.log('  1. Review bundled output');
  console.log('  2. Deploy using clasp or your deployment script');
}

// Run build
build().catch((error) => {
  console.error('❌ Build failed:', error);
  process.exit(1);
});

