$schema: http://json-schema.org/draft-07/schema#
title: BasicChartDomain
description: The domain of a chart. For example, if charting stock prices over time,
  this would be the date.
type: object
properties:
  domain:
    $ref: ChartData
    description: The data of the domain. For example, if charting stock prices over
      time, this is the data representing the dates.
  reversed:
    description: True to reverse the order of the domain values (horizontal axis).
    type: boolean
