$schema: http://json-schema.org/draft-07/schema#
title: BubbleChartSpec
description: A bubble chart.
type: object
properties:
  legendPosition:
    description: Where the legend of the chart should be drawn.
    enum:
    - BUBBLE_CHART_LEGEND_POSITION_UNSPECIFIED
    - BOTTOM_LEGEND
    - LEFT_LEGEND
    - RIGHT_LEGEND
    - TOP_LEGEND
    - NO_LEGEND
    - INSIDE_LEGEND
    enumDescriptions:
    - Default value, do not use.
    - The legend is rendered on the bottom of the chart.
    - The legend is rendered on the left of the chart.
    - The legend is rendered on the right of the chart.
    - The legend is rendered on the top of the chart.
    - No legend is rendered.
    - The legend is rendered inside the chart area.
    type: string
  bubbleBorderColor:
    $ref: Color
    description: 'The bubble border color. Deprecated: Use bubble_border_color_style.'
    deprecated: true
  bubbleLabels:
    $ref: ChartData
    description: The data containing the bubble labels. These do not need to be unique.
  bubbleBorderColorStyle:
    description: The bubble border color. If bubble_border_color is also set, this
      field takes precedence.
    $ref: ColorStyle
  bubbleOpacity:
    description: The opacity of the bubbles between 0 and 1.0. 0 is fully transparent
      and 1 is fully opaque.
    format: float
    type: number
  groupIds:
    description: The data containing the bubble group IDs. All bubbles with the same
      group ID are drawn in the same color. If bubble_sizes is specified then this
      field must also be specified but may contain blank values. This field is optional.
    $ref: ChartData
  domain:
    $ref: ChartData
    description: The data containing the bubble x-values. These values locate the
      bubbles in the chart horizontally.
  series:
    description: The data containing the bubble y-values. These values locate the
      bubbles in the chart vertically.
    $ref: ChartData
  bubbleSizes:
    description: The data containing the bubble sizes. Bubble sizes are used to draw
      the bubbles at different sizes relative to each other. If specified, group_ids
      must also be specified. This field is optional.
    $ref: ChartData
  bubbleTextStyle:
    description: The format of the text inside the bubbles. Strikethrough, underline,
      and link are not supported.
    $ref: TextFormat
  bubbleMaxRadiusSize:
    description: The max radius size of the bubbles, in pixels. If specified, the
      field must be a positive value.
    format: int32
    type: integer
  bubbleMinRadiusSize:
    type: integer
    description: The minimum radius size of the bubbles, in pixels. If specific, the
      field must be a positive value.
    format: int32
