description: Creates a role.
httpMethod: POST
path: admin/directory/v1/customer/{customer}/roles
scopes:
- https://www.googleapis.com/auth/admin.directory.rolemanagement
request:
  $ref: Role
parameters:
  customer:
    description: Immutable ID of the Google Workspace account.
    location: path
    required: true
    type: string
response:
  $ref: Role
