$schema: http://json-schema.org/draft-07/schema#
title: QuizSettings
description: Settings related to quiz forms and grading. These must be updated with
  the UpdateSettingsRequest.
type: object
properties:
  isQuiz:
    type: boolean
    description: Whether this form is a quiz or not. When true, responses are graded
      based on question Grading. Upon setting to false, all question Grading is deleted.
