# generated by datamodel-codegen:
#   filename:  forms.yaml
#   timestamp: 2026-03-21T18:41:26+00:00


from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, Field, RootModel


class FormsApiSchemas(RootModel[Any]):
    root: Annotated[Any, Field(title='Forms API Schemas')]


class FileUploadAnswer(BaseModel):
    """
    Info for a single file submitted to a file upload question.
    """

    file_name: Annotated[str | None, Field(alias='fileName')] = None
    """
    Output only. The file name, as stored in Google Drive on upload.
    """
    mime_type: Annotated[str | None, Field(alias='mimeType')] = None
    """
    Output only. The MIME type of the file, as stored in Google Drive on upload.
    """
    file_id: Annotated[str | None, Field(alias='fileId')] = None
    """
    Output only. The ID of the Google Drive file.
    """


class FileUploadAnswers(BaseModel):
    """
    All submitted files for a FileUpload question.
    """

    answers: list[FileUploadAnswer] | None = None
    """
    Output only. All submitted files for a FileUpload question.
    """


class TextAnswer(BaseModel):
    """
    An answer to a question represented as text.
    """

    value: str | None = None
    """
    Output only. The answer value. Formatting used for different kinds of question: * ChoiceQuestion * `RADIO` or `DROP_DOWN`: A single string corresponding to the option that was selected. * `CHECKBOX`: Multiple strings corresponding to each option that was selected. * TextQuestion: The text that the user entered. * ScaleQuestion: A string containing the number that was selected. * DateQuestion * Without time or year: MM-DD e.g. "05-19" * With year: YYYY-MM-DD e.g. "1986-05-19" * With time: MM-DD HH:MM e.g. "05-19 14:51" * With year and time: YYYY-MM-DD HH:MM e.g. "1986-05-19 14:51" * TimeQuestion: String with time or duration in HH:MM format e.g. "14:51" * RowQuestion within QuestionGroupItem: The answer for each row of a QuestionGroupItem is represented as a separate Answer. Each will contain one string for `RADIO`-type choices or multiple strings for `CHECKBOX` choices.
    """


class TextAnswers(BaseModel):
    """
    A question's answers as text.
    """

    answers: list[TextAnswer] | None = None
    """
    Output only. Answers to a question. For multiple-value ChoiceQuestions, each answer is a separate value.
    """


class CloudPubsubTopic(BaseModel):
    """
    A Pub/Sub topic.
    """

    topic_name: Annotated[str | None, Field(alias='topicName')] = None
    """
    Required. A fully qualified Pub/Sub topic name to publish the events to. This topic must be owned by the calling project and already exist in Pub/Sub.
    """


class Empty(BaseModel):
    """
    A generic empty message that you can re-use to avoid defining duplicated empty messages in your APIs. A typical example is to use it as the request or the response type of an API method. For instance: service Foo { rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty); }
    """


class Location(BaseModel):
    """
    A specific location in a form.
    """

    index: int | None = None
    """
    The index of an item in the form. This must be in the range [0..*N*), where *N* is the number of items in the form.
    """


class GoToAction(Enum):
    """
    Section navigation type.
    """

    go_to_action_unspecified = 'GO_TO_ACTION_UNSPECIFIED'
    next_section = 'NEXT_SECTION'
    restart_form = 'RESTART_FORM'
    submit_form = 'SUBMIT_FORM'


class WriteControl(BaseModel):
    """
    Provides control over how write requests are executed.
    """

    required_revision_id: Annotated[str | None, Field(alias='requiredRevisionId')] = (
        None
    )
    """
    The revision ID of the form that the write request is applied to. If this is not the latest revision of the form, the request is not processed and returns a 400 bad request error.
    """
    target_revision_id: Annotated[str | None, Field(alias='targetRevisionId')] = None
    """
    The target revision ID of the form that the write request is applied to. If changes have occurred after this revision, the changes in this update request are transformed against those changes. This results in a new revision of the form that incorporates both the changes in the request and the intervening changes, with the server resolving conflicting changes. The target revision ID may only be used to write to recent versions of a form. If the target revision is too far behind the latest revision, the request is not processed and returns a 400 (Bad Request Error). The request may be retried after reading the latest version of the form. In most cases a target revision ID remains valid for several minutes after it is read, but for frequently-edited forms this window may be shorter.
    """


class EmailCollectionType(Enum):
    """
    Optional. The setting that determines whether the form collects email addresses from respondents.
    """

    email_collection_type_unspecified = 'EMAIL_COLLECTION_TYPE_UNSPECIFIED'
    do_not_collect = 'DO_NOT_COLLECT'
    verified = 'VERIFIED'
    responder_input = 'RESPONDER_INPUT'


class Info(BaseModel):
    """
    The general information for a form.
    """

    description: str | None = None
    """
    The description of the form.
    """
    document_title: Annotated[str | None, Field(alias='documentTitle')] = None
    """
    Output only. The title of the document which is visible in Drive. If Info.title is empty, `document_title` may appear in its place in the Google Forms UI and be visible to responders. `document_title` can be set on create, but cannot be modified by a batchUpdate request. Please use the [Google Drive API](https://developers.google.com/drive/api/v3/reference/files/update) if you need to programmatically update `document_title`.
    """
    title: str | None = None
    """
    Required. The title of the form which is visible to responders.
    """


class CorrectAnswer(BaseModel):
    """
    A single correct answer for a question. For multiple-valued (`CHECKBOX`) questions, several `CorrectAnswer`s may be needed to represent a single correct response option.
    """

    value: str | None = None
    """
    Required. The correct answer value. See the documentation for TextAnswer.value for details on how various value types are formatted.
    """


class CorrectAnswers(BaseModel):
    """
    The answer key for a question.
    """

    answers: list[CorrectAnswer] | None = None
    """
    A list of correct answers. A quiz response can be automatically graded based on these answers. For single-valued questions, a response is marked correct if it matches any value in this list (in other words, multiple correct answers are possible). For multiple-valued (`CHECKBOX`) questions, a response is marked correct if it contains exactly the values in this list.
    """


class QuizSettings(BaseModel):
    """
    Settings related to quiz forms and grading. These must be updated with the UpdateSettingsRequest.
    """

    is_quiz: Annotated[bool | None, Field(alias='isQuiz')] = None
    """
    Whether this form is a quiz or not. When true, responses are graded based on question Grading. Upon setting to false, all question Grading is deleted.
    """


class PageBreakItem(BaseModel):
    """
    A page break. The title and description of this item are shown at the top of the new page.
    """


class TextItem(BaseModel):
    """
    A text item.
    """


class Alignment(Enum):
    """
    Position of the media.
    """

    alignment_unspecified = 'ALIGNMENT_UNSPECIFIED'
    left = 'LEFT'
    right = 'RIGHT'
    center = 'CENTER'


class MediaProperties(BaseModel):
    """
    Properties of the media.
    """

    alignment: Alignment | None = None
    """
    Position of the media.
    """
    width: int | None = None
    """
    The width of the media in pixels. When the media is displayed, it is scaled to the smaller of this value or the width of the displayed form. The original aspect ratio of the media is preserved. If a width is not specified when the media is added to the form, it is set to the width of the media source. Width must be between 0 and 740, inclusive. Setting width to 0 or unspecified is only permitted when updating the media source.
    """


class TextLink(BaseModel):
    """
    Link for text.
    """

    uri: str | None = None
    """
    Required. The URI.
    """
    display_text: Annotated[str | None, Field(alias='displayText')] = None
    """
    Required. Display text for the URI.
    """


class Video(BaseModel):
    """
    Data representing a video.
    """

    youtube_uri: Annotated[str | None, Field(alias='youtubeUri')] = None
    """
    Required. A YouTube URI.
    """
    properties: MediaProperties | None = None
    """
    Properties of a video.
    """


class VideoLink(BaseModel):
    """
    Link to a video.
    """

    youtube_uri: Annotated[str | None, Field(alias='youtubeUri')] = None
    """
    The URI of a YouTube video.
    """
    display_text: Annotated[str | None, Field(alias='displayText')] = None
    """
    Required. The display text for the link.
    """


class PublishState(BaseModel):
    """
    The publishing state of a form.
    """

    is_published: Annotated[bool | None, Field(alias='isPublished')] = None
    """
    Required. Whether the form is published and visible to others.
    """
    is_accepting_responses: Annotated[
        bool | None, Field(alias='isAcceptingResponses')
    ] = None
    """
    Required. Whether the form accepts responses. If `is_published` is set to `false`, this field is forced to `false`.
    """


class Type(Enum):
    """
    Required. The type of choice question.
    """

    choice_type_unspecified = 'CHOICE_TYPE_UNSPECIFIED'
    radio = 'RADIO'
    checkbox = 'CHECKBOX'
    drop_down = 'DROP_DOWN'


class DateQuestion(BaseModel):
    """
    A date question. Date questions default to just month + day.
    """

    include_time: Annotated[bool | None, Field(alias='includeTime')] = None
    """
    Whether to include the time as part of the question.
    """
    include_year: Annotated[bool | None, Field(alias='includeYear')] = None
    """
    Whether to include the year as part of the question.
    """


class Type1(Enum):
    file_type_unspecified = 'FILE_TYPE_UNSPECIFIED'
    any = 'ANY'
    document = 'DOCUMENT'
    presentation = 'PRESENTATION'
    spreadsheet = 'SPREADSHEET'
    drawing = 'DRAWING'
    pdf = 'PDF'
    image = 'IMAGE'
    video = 'VIDEO'
    audio = 'AUDIO'


class FileUploadQuestion(BaseModel):
    """
    A file upload question. The API currently does not support creating file upload questions.
    """

    max_files: Annotated[int | None, Field(alias='maxFiles')] = None
    """
    Maximum number of files that can be uploaded for this question in a single response.
    """
    max_file_size: Annotated[str | None, Field(alias='maxFileSize')] = None
    """
    Maximum number of bytes allowed for any single file uploaded to this question.
    """
    folder_id: Annotated[str | None, Field(alias='folderId')] = None
    """
    Required. The ID of the Drive folder where uploaded files are stored.
    """
    types: list[Type1] | None = None
    """
    File types accepted by this question.
    """


class IconType(Enum):
    """
    Required. The icon type to use for the rating.
    """

    rating_icon_type_unspecified = 'RATING_ICON_TYPE_UNSPECIFIED'
    star = 'STAR'
    heart = 'HEART'
    thumb_up = 'THUMB_UP'


class RatingQuestion(BaseModel):
    """
    A rating question. The user has a range of icons to choose from.
    """

    rating_scale_level: Annotated[int | None, Field(alias='ratingScaleLevel')] = None
    """
    Required. The rating scale level of the rating question.
    """
    icon_type: Annotated[IconType | None, Field(alias='iconType')] = None
    """
    Required. The icon type to use for the rating.
    """


class RowQuestion(BaseModel):
    """
    Configuration for a question that is part of a question group.
    """

    title: str | None = None
    """
    Required. The title for the single row in the QuestionGroupItem.
    """


class ScaleQuestion(BaseModel):
    """
    A scale question. The user has a range of numeric values to choose from.
    """

    low: int | None = None
    """
    Required. The lowest possible value for the scale.
    """
    low_label: Annotated[str | None, Field(alias='lowLabel')] = None
    """
    The label to display describing the lowest point on the scale.
    """
    high_label: Annotated[str | None, Field(alias='highLabel')] = None
    """
    The label to display describing the highest point on the scale.
    """
    high: int | None = None
    """
    Required. The highest possible value for the scale.
    """


class TextQuestion(BaseModel):
    """
    A text-based question.
    """

    paragraph: bool | None = None
    """
    Whether the question is a paragraph question or not. If not, the question is a short text question.
    """


class TimeQuestion(BaseModel):
    """
    A time question.
    """

    duration: bool | None = None
    """
    `true` if the question is about an elapsed time. Otherwise it is about a time of day.
    """


class DeleteItemRequest(BaseModel):
    """
    Delete an item in a form.
    """

    location: Location | None = None
    """
    Required. The location of the item to delete.
    """


class MoveItemRequest(BaseModel):
    """
    Move an item in a form.
    """

    original_location: Annotated[Location | None, Field(alias='originalLocation')] = (
        None
    )
    """
    Required. The location of the item to move.
    """
    new_location: Annotated[Location | None, Field(alias='newLocation')] = None
    """
    Required. The new location for the item.
    """


class UpdateFormInfoRequest(BaseModel):
    """
    Update Form's Info.
    """

    info: Info | None = None
    """
    The info to update.
    """
    update_mask: Annotated[str | None, Field(alias='updateMask')] = None
    """
    Required. Only values named in this mask are changed. At least one field must be specified. The root `info` is implied and should not be specified. A single `"*"` can be used as short-hand for updating every field.
    """


class CreateItemResponse(BaseModel):
    """
    The result of creating an item.
    """

    question_id: Annotated[list[str] | None, Field(alias='questionId')] = None
    """
    The ID of the question created as part of this item, for a question group it lists IDs of all the questions created for this item.
    """
    item_id: Annotated[str | None, Field(alias='itemId')] = None
    """
    The ID of the created item.
    """


class RenewWatchRequest(BaseModel):
    """
    Renew an existing Watch for seven days.
    """


class EventType(Enum):
    """
    Required. Which event type to watch for.
    """

    event_type_unspecified = 'EVENT_TYPE_UNSPECIFIED'
    schema = 'SCHEMA'
    responses = 'RESPONSES'


class State(Enum):
    """
    Output only. The current state of the watch. Additional details about suspended watches can be found by checking the `error_type`.
    """

    state_unspecified = 'STATE_UNSPECIFIED'
    active = 'ACTIVE'
    suspended = 'SUSPENDED'


class ErrorType(Enum):
    """
    Output only. The most recent error type for an attempted delivery. To begin watching the form again a call can be made to watches.renew which also clears this error information.
    """

    error_type_unspecified = 'ERROR_TYPE_UNSPECIFIED'
    project_not_authorized = 'PROJECT_NOT_AUTHORIZED'
    no_user_access = 'NO_USER_ACCESS'
    other_errors = 'OTHER_ERRORS'


class WatchTarget(BaseModel):
    """
    The target for notification delivery.
    """

    topic: CloudPubsubTopic | None = None
    """
    A Pub/Sub topic. To receive notifications, the topic must grant publish privileges to the Forms service account `serviceAccount:forms-notifications@system.gserviceaccount.com`. Only the project that owns a topic may create a watch with it. Pub/Sub delivery guarantees should be considered.
    """


class Response(BaseModel):
    """
    A single response from an update.
    """

    create_item: Annotated[CreateItemResponse | None, Field(alias='createItem')] = None
    """
    The result of creating an item.
    """


class FormSettings(BaseModel):
    """
    A form's settings.
    """

    email_collection_type: Annotated[
        EmailCollectionType | None, Field(alias='emailCollectionType')
    ] = None
    """
    Optional. The setting that determines whether the form collects email addresses from respondents.
    """
    quiz_settings: Annotated[QuizSettings | None, Field(alias='quizSettings')] = None
    """
    Settings related to quiz forms and grading.
    """


class ExtraMaterial(BaseModel):
    """
    Supplementary material to the feedback.
    """

    link: TextLink | None = None
    """
    Text feedback.
    """
    video: VideoLink | None = None
    """
    Video feedback.
    """


class Feedback(BaseModel):
    """
    Feedback for a respondent about their response to a question.
    """

    text: str | None = None
    """
    Required. The main text of the feedback.
    """
    material: list[ExtraMaterial] | None = None
    """
    Additional information provided as part of the feedback, often used to point the respondent to more reading and resources.
    """


class Grade(BaseModel):
    """
    Grade information associated with a respondent's answer to a question.
    """

    score: float | None = None
    """
    Output only. The numeric score awarded for the answer.
    """
    feedback: Feedback | None = None
    """
    Output only. Additional feedback given for an answer.
    """
    correct: bool | None = None
    """
    Output only. Whether the question was answered correctly or not. A zero-point score is not enough to infer incorrectness, since a correctly answered question could be worth zero points.
    """


class Grading(BaseModel):
    """
    Grading for a single question
    """

    point_value: Annotated[int | None, Field(alias='pointValue')] = None
    """
    Required. The maximum number of points a respondent can automatically get for a correct answer. This must not be negative.
    """
    correct_answers: Annotated[CorrectAnswers | None, Field(alias='correctAnswers')] = (
        None
    )
    """
    Required. The answer key for the question. Responses are automatically graded based on this field.
    """
    when_right: Annotated[Feedback | None, Field(alias='whenRight')] = None
    """
    The feedback displayed for correct responses. This feedback can only be set for multiple choice questions that have correct answers provided.
    """
    general_feedback: Annotated[Feedback | None, Field(alias='generalFeedback')] = None
    """
    The feedback displayed for all answers. This is commonly used for short answer questions when a quiz owner wants to quickly give respondents some sense of whether they answered the question correctly before they've had a chance to officially grade the response. General feedback cannot be set for automatically graded multiple choice questions.
    """
    when_wrong: Annotated[Feedback | None, Field(alias='whenWrong')] = None
    """
    The feedback displayed for incorrect responses. This feedback can only be set for multiple choice questions that have correct answers provided.
    """


class VideoItem(BaseModel):
    """
    An item containing a video.
    """

    video: Video | None = None
    """
    Required. The video displayed in the item.
    """
    caption: str | None = None
    """
    The text displayed below the video.
    """


class Image(BaseModel):
    """
    Data representing an image.
    """

    source_uri: Annotated[str | None, Field(alias='sourceUri')] = None
    """
    Input only. The source URI is the URI used to insert the image. The source URI can be empty when fetched.
    """
    alt_text: Annotated[str | None, Field(alias='altText')] = None
    """
    A description of the image that is shown on hover and read by screenreaders.
    """
    content_uri: Annotated[str | None, Field(alias='contentUri')] = None
    """
    Output only. A URI from which you can download the image; this is valid only for a limited time.
    """
    properties: MediaProperties | None = None
    """
    Properties of an image.
    """


class PublishSettings(BaseModel):
    """
    The publishing settings of a form.
    """

    publish_state: Annotated[PublishState | None, Field(alias='publishState')] = None
    """
    Optional. The publishing state of a form. When updating `publish_state`, both `is_published` and `is_accepting_responses` must be set. However, setting `is_accepting_responses` to `true` and `is_published` to `false` isn't supported and returns an error.
    """


class SetPublishSettingsRequest(BaseModel):
    """
    Updates the publish settings of a Form.
    """

    publish_settings: Annotated[
        PublishSettings | None, Field(alias='publishSettings')
    ] = None
    """
    Required. The desired publish settings to apply to the form.
    """
    update_mask: Annotated[str | None, Field(alias='updateMask')] = None
    """
    Optional. The `publish_settings` fields to update. This field mask accepts the following values: * `publish_state`: Updates or replaces all `publish_state` settings. * `"*"`: Updates or replaces all `publish_settings` fields.
    """


class UpdateSettingsRequest(BaseModel):
    """
    Update Form's FormSettings.
    """

    settings: FormSettings | None = None
    """
    Required. The settings to update with.
    """
    update_mask: Annotated[str | None, Field(alias='updateMask')] = None
    """
    Required. Only values named in this mask are changed. At least one field must be specified. The root `settings` is implied and should not be specified. A single `"*"` can be used as short-hand for updating every field.
    """


class SetPublishSettingsResponse(BaseModel):
    """
    The response of a SetPublishSettings request.
    """

    form_id: Annotated[str | None, Field(alias='formId')] = None
    """
    Required. The ID of the Form. This is same as the Form.form_id field.
    """
    publish_settings: Annotated[
        PublishSettings | None, Field(alias='publishSettings')
    ] = None
    """
    The publish settings of the form.
    """


class Watch(BaseModel):
    """
    A watch for events for a form. When the designated event happens, a notification will be published to the specified target. The notification's attributes will include a `formId` key that has the ID of the watched form and an `eventType` key that has the string of the type. Messages are sent with at-least-once delivery and are only dropped in extraordinary circumstances. Typically all notifications should be reliably delivered within a few seconds; however, in some situations notifications may be delayed. A watch expires seven days after it is created unless it is renewed with watches.renew
    """

    target: WatchTarget | None = None
    """
    Required. Where to send the notification.
    """
    event_type: Annotated[EventType | None, Field(alias='eventType')] = None
    """
    Required. Which event type to watch for.
    """
    id: str | None = None
    """
    Output only. The ID of this watch. See notes on CreateWatchRequest.watch_id.
    """
    state: State | None = None
    """
    Output only. The current state of the watch. Additional details about suspended watches can be found by checking the `error_type`.
    """
    create_time: Annotated[str | None, Field(alias='createTime')] = None
    """
    Output only. Timestamp of when this was created.
    """
    expire_time: Annotated[str | None, Field(alias='expireTime')] = None
    """
    Output only. Timestamp for when this will expire. Each watches.renew call resets this to seven days in the future.
    """
    error_type: Annotated[ErrorType | None, Field(alias='errorType')] = None
    """
    Output only. The most recent error type for an attempted delivery. To begin watching the form again a call can be made to watches.renew which also clears this error information.
    """


class Answer(BaseModel):
    """
    The submitted answer for a question.
    """

    file_upload_answers: Annotated[
        FileUploadAnswers | None, Field(alias='fileUploadAnswers')
    ] = None
    """
    Output only. The answers to a file upload question.
    """
    question_id: Annotated[str | None, Field(alias='questionId')] = None
    """
    Output only. The question's ID. See also Question.question_id.
    """
    grade: Grade | None = None
    """
    Output only. The grade for the answer if the form was a quiz.
    """
    text_answers: Annotated[TextAnswers | None, Field(alias='textAnswers')] = None
    """
    Output only. The specific answers as text.
    """


class Option(BaseModel):
    """
    An option for a Choice question.
    """

    is_other: Annotated[bool | None, Field(alias='isOther')] = None
    """
    Whether the option is "other". Currently only applies to `RADIO` and `CHECKBOX` choice types, but is not allowed in a QuestionGroupItem.
    """
    go_to_section_id: Annotated[str | None, Field(alias='goToSectionId')] = None
    """
    Item ID of section header to go to.
    """
    image: Image | None = None
    """
    Display image as an option.
    """
    go_to_action: Annotated[GoToAction | None, Field(alias='goToAction')] = None
    """
    Section navigation type.
    """
    value: str | None = None
    """
    Required. The choice as presented to the user.
    """


class FormResponse(BaseModel):
    """
    A form response.
    """

    form_id: Annotated[str | None, Field(alias='formId')] = None
    """
    Output only. The form ID.
    """
    last_submitted_time: Annotated[str | None, Field(alias='lastSubmittedTime')] = None
    """
    Output only. Timestamp for the most recent time the response was submitted. Does not track changes to grades.
    """
    respondent_email: Annotated[str | None, Field(alias='respondentEmail')] = None
    """
    Output only. The email address (if collected) for the respondent.
    """
    answers: dict[str, Answer] | None = None
    """
    Output only. The actual answers to the questions, keyed by question_id.
    """
    response_id: Annotated[str | None, Field(alias='responseId')] = None
    """
    Output only. The response ID.
    """
    create_time: Annotated[str | None, Field(alias='createTime')] = None
    """
    Output only. Timestamp for the first time the response was submitted.
    """
    total_score: Annotated[float | None, Field(alias='totalScore')] = None
    """
    Output only. The total number of points the respondent received for their submission Only set if the form was a quiz and the response was graded. This includes points automatically awarded via autograding adjusted by any manual corrections entered by the form owner.
    """


class ImageItem(BaseModel):
    """
    An item containing an image.
    """

    image: Image | None = None
    """
    Required. The image displayed in the item.
    """


class ChoiceQuestion(BaseModel):
    """
    A radio/checkbox/dropdown question.
    """

    type: Type | None = None
    """
    Required. The type of choice question.
    """
    options: list[Option] | None = None
    """
    Required. List of options that a respondent must choose from.
    """
    shuffle: bool | None = None
    """
    Whether the options should be displayed in random order for different instances of the quiz. This is often used to prevent cheating by respondents who might be looking at another respondent's screen, or to address bias in a survey that might be introduced by always putting the same options first or last.
    """


class Grid(BaseModel):
    """
    A grid of choices (radio or check boxes) with each row constituting a separate question. Each row has the same choices, which are shown as the columns.
    """

    columns: ChoiceQuestion | None = None
    """
    Required. The choices shared by each question in the grid. In other words, the values of the columns. Only `CHECK_BOX` and `RADIO` choices are allowed.
    """
    shuffle_questions: Annotated[bool | None, Field(alias='shuffleQuestions')] = None
    """
    If `true`, the questions are randomly ordered. In other words, the rows appear in a different order for every respondent.
    """


class Question(BaseModel):
    """
    Any question. The specific type of question is known by its `kind`.
    """

    scale_question: Annotated[ScaleQuestion | None, Field(alias='scaleQuestion')] = None
    """
    A respondent can choose a number from a range.
    """
    rating_question: Annotated[RatingQuestion | None, Field(alias='ratingQuestion')] = (
        None
    )
    """
    A respondent can choose a rating from a pre-defined set of icons.
    """
    time_question: Annotated[TimeQuestion | None, Field(alias='timeQuestion')] = None
    """
    A respondent can enter a time.
    """
    question_id: Annotated[str | None, Field(alias='questionId')] = None
    """
    Read only. The question ID. On creation, it can be provided but the ID must not be already used in the form. If not provided, a new ID is assigned.
    """
    required: bool | None = None
    """
    Whether the question must be answered in order for a respondent to submit their response.
    """
    grading: Grading | None = None
    """
    Grading setup for the question.
    """
    row_question: Annotated[RowQuestion | None, Field(alias='rowQuestion')] = None
    """
    A row of a QuestionGroupItem.
    """
    file_upload_question: Annotated[
        FileUploadQuestion | None, Field(alias='fileUploadQuestion')
    ] = None
    """
    A respondent can upload one or more files.
    """
    text_question: Annotated[TextQuestion | None, Field(alias='textQuestion')] = None
    """
    A respondent can enter a free text response.
    """
    date_question: Annotated[DateQuestion | None, Field(alias='dateQuestion')] = None
    """
    A respondent can enter a date.
    """
    choice_question: Annotated[ChoiceQuestion | None, Field(alias='choiceQuestion')] = (
        None
    )
    """
    A respondent can choose from a pre-defined set of options.
    """


class ListFormResponsesResponse(BaseModel):
    """
    Response to a ListFormResponsesRequest.
    """

    responses: list[FormResponse] | None = None
    """
    The returned form responses. Note: The `formId` field is not returned in the `FormResponse` object for list requests.
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    If set, there are more responses. To get the next page of responses, provide this as `page_token` in a future request.
    """


class CreateWatchRequest(BaseModel):
    """
    Create a new watch.
    """

    watch: Watch | None = None
    """
    Required. The watch object. No ID should be set on this object; use `watch_id` instead.
    """
    watch_id: Annotated[str | None, Field(alias='watchId')] = None
    """
    The ID to use for the watch. If specified, the ID must not already be in use. If not specified, an ID is generated. This value should be 4-63 characters, and valid characters are /a-z-/.
    """


class ListWatchesResponse(BaseModel):
    """
    The response of a ListWatchesRequest.
    """

    watches: list[Watch] | None = None
    """
    The returned watches.
    """


class QuestionGroupItem(BaseModel):
    """
    Defines a question that comprises multiple questions grouped together.
    """

    grid: Grid | None = None
    """
    The question group is a grid with rows of multiple choice questions that share the same options. When `grid` is set, all questions in the group must be of kind `row`.
    """
    questions: list[Question] | None = None
    """
    Required. A list of questions that belong in this question group. A question must only belong to one group. The `kind` of the group may affect what types of questions are allowed.
    """
    image: Image | None = None
    """
    The image displayed within the question group above the specific questions.
    """


class QuestionItem(BaseModel):
    """
    A form item containing a single question.
    """

    question: Question | None = None
    """
    Required. The displayed question.
    """
    image: Image | None = None
    """
    The image displayed within the question.
    """


class Item(BaseModel):
    """
    A single item of the form. `kind` defines which kind of item it is.
    """

    question_item: Annotated[QuestionItem | None, Field(alias='questionItem')] = None
    """
    Poses a question to the user.
    """
    question_group_item: Annotated[
        QuestionGroupItem | None, Field(alias='questionGroupItem')
    ] = None
    """
    Poses one or more questions to the user with a single major prompt.
    """
    item_id: Annotated[str | None, Field(alias='itemId')] = None
    """
    The item ID. On creation, it can be provided but the ID must not be already used in the form. If not provided, a new ID is assigned.
    """
    page_break_item: Annotated[PageBreakItem | None, Field(alias='pageBreakItem')] = (
        None
    )
    """
    Starts a new page with a title.
    """
    title: str | None = None
    """
    The title of the item.
    """
    image_item: Annotated[ImageItem | None, Field(alias='imageItem')] = None
    """
    Displays an image on the page.
    """
    video_item: Annotated[VideoItem | None, Field(alias='videoItem')] = None
    """
    Displays a video on the page.
    """
    text_item: Annotated[TextItem | None, Field(alias='textItem')] = None
    """
    Displays a title and description on the page.
    """
    description: str | None = None
    """
    The description of the item.
    """


class CreateItemRequest(BaseModel):
    """
    Create an item in a form.
    """

    item: Item | None = None
    """
    Required. The item to create.
    """
    location: Location | None = None
    """
    Required. Where to place the new item.
    """


class UpdateItemRequest(BaseModel):
    """
    Update an item in a form.
    """

    update_mask: Annotated[str | None, Field(alias='updateMask')] = None
    """
    Required. Only values named in this mask are changed.
    """
    item: Item | None = None
    """
    Required. New values for the item. Note that item and question IDs are used if they are provided (and are in the field mask). If an ID is blank (and in the field mask) a new ID is generated. This means you can modify an item by getting the form via forms.get, modifying your local copy of that item to be how you want it, and using UpdateItemRequest to write it back, with the IDs being the same (or not in the field mask).
    """
    location: Location | None = None
    """
    Required. The location identifying the item to update.
    """


class Request(BaseModel):
    """
    The kinds of update requests that can be made.
    """

    update_form_info: Annotated[
        UpdateFormInfoRequest | None, Field(alias='updateFormInfo')
    ] = None
    """
    Update Form's Info.
    """
    update_settings: Annotated[
        UpdateSettingsRequest | None, Field(alias='updateSettings')
    ] = None
    """
    Updates the Form's settings.
    """
    move_item: Annotated[MoveItemRequest | None, Field(alias='moveItem')] = None
    """
    Move an item to a specified location.
    """
    update_item: Annotated[UpdateItemRequest | None, Field(alias='updateItem')] = None
    """
    Update an item.
    """
    delete_item: Annotated[DeleteItemRequest | None, Field(alias='deleteItem')] = None
    """
    Delete an item.
    """
    create_item: Annotated[CreateItemRequest | None, Field(alias='createItem')] = None
    """
    Create a new item.
    """


class Form(BaseModel):
    """
    A Google Forms document. A form is created in Drive, and deleting a form or changing its access protections is done via the [Drive API](https://developers.google.com/drive/api/v3/about-sdk).
    """

    publish_settings: Annotated[
        PublishSettings | None, Field(alias='publishSettings')
    ] = None
    """
    Output only. The publishing settings for a form. This field isn't set for legacy forms because they don't have the publish_settings field. All newly created forms support publish settings. Forms with publish_settings value set can call SetPublishSettings API to publish or unpublish the form.
    """
    items: list[Item] | None = None
    """
    Required. A list of the form's items, which can include section headers, questions, embedded media, etc.
    """
    settings: FormSettings | None = None
    """
    The form's settings. This must be updated with UpdateSettingsRequest; it is ignored during CreateForm and UpdateFormInfoRequest.
    """
    revision_id: Annotated[str | None, Field(alias='revisionId')] = None
    """
    Output only. The revision ID of the form. Used in the WriteControl in update requests to identify the revision on which the changes are based. The format of the revision ID may change over time, so it should be treated opaquely. A returned revision ID is only guaranteed to be valid for 24 hours after it has been returned and cannot be shared across users. If the revision ID is unchanged between calls, then the form *content* has not changed. Conversely, a changed ID (for the same form and user) usually means the form *content* has been updated; however, a changed ID can also be due to internal factors such as ID format changes. Form content excludes form metadata, including: * sharing settings (who has access to the form) * publish_settings (if the form supports publishing and if it is published)
    """
    responder_uri: Annotated[str | None, Field(alias='responderUri')] = None
    """
    Output only. The form URI to share with responders. This opens a page that allows the user to submit responses but not edit the questions. For forms that have publish_settings value set, this is the published form URI.
    """
    linked_sheet_id: Annotated[str | None, Field(alias='linkedSheetId')] = None
    """
    Output only. The ID of the linked Google Sheet which is accumulating responses from this Form (if such a Sheet exists).
    """
    info: Info | None = None
    """
    Required. The title and description of the form.
    """
    form_id: Annotated[str | None, Field(alias='formId')] = None
    """
    Output only. The form ID.
    """


class BatchUpdateFormRequest(BaseModel):
    """
    A batch of updates to perform on a form. All the specified updates are made or none of them are.
    """

    include_form_in_response: Annotated[
        bool | None, Field(alias='includeFormInResponse')
    ] = None
    """
    Whether to return an updated version of the model in the response.
    """
    requests: list[Request] | None = None
    """
    Required. The update requests of this batch.
    """
    write_control: Annotated[WriteControl | None, Field(alias='writeControl')] = None
    """
    Provides control over how write requests are executed.
    """


class BatchUpdateFormResponse(BaseModel):
    """
    Response to a BatchUpdateFormRequest.
    """

    replies: list[Response] | None = None
    """
    The reply of the updates. This maps 1:1 with the update requests, although replies to some requests may be empty.
    """
    form: Form | None = None
    """
    Based on the bool request field `include_form_in_response`, a form with all applied mutations/updates is returned or not. This may be later than the revision ID created by these changes.
    """
    write_control: Annotated[WriteControl | None, Field(alias='writeControl')] = None
    """
    The updated write control after applying the request.
    """
