# generated by datamodel-codegen:
#   filename:  script.yaml
#   timestamp: 2026-03-21T18:41:24+00:00


from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, Field, RootModel


class ScriptApiSchemas(RootModel[Any]):
    root: Annotated[Any, Field(title='Script API Schemas')]


class CreateProjectRequest(BaseModel):
    """
    Request to create a script project.
    """

    title: str | None = None
    """
    The title for the project.
    """
    parent_id: Annotated[str | None, Field(alias='parentId')] = None
    """
    The Drive ID of a parent file that the created script project is bound to. This is usually the ID of a Google Doc, Google Sheet, Google Form, or Google Slides file. If not set, a standalone script project is created.
    """


class Empty(BaseModel):
    """
    A generic empty message that you can re-use to avoid defining duplicated empty messages in your APIs. A typical example is to use it as the request or the response type of an API method. For instance: service Foo { rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty); }
    """


class GoogleAppsScriptTypeUser(BaseModel):
    """
    A simple user profile resource.
    """

    email: str | None = None
    """
    The user's identifying email address.
    """
    name: str | None = None
    """
    The user's display name.
    """
    photo_url: Annotated[str | None, Field(alias='photoUrl')] = None
    """
    The user's photo.
    """
    domain: str | None = None
    """
    The user's domain.
    """


class MetricsValue(BaseModel):
    """
    Metrics value that holds number of executions counted.
    """

    start_time: Annotated[str | None, Field(alias='startTime')] = None
    """
    Required field indicating the start time of the interval.
    """
    end_time: Annotated[str | None, Field(alias='endTime')] = None
    """
    Required field indicating the end time of the interval.
    """
    value: str | None = None
    """
    Indicates the number of executions counted.
    """


class ScriptStackTraceElement(BaseModel):
    """
    A stack trace through the script that shows where the execution failed.
    """

    function: str | None = None
    """
    The name of the function that failed.
    """
    line_number: Annotated[int | None, Field(alias='lineNumber')] = None
    """
    The line number where the script failed.
    """


class Status(BaseModel):
    """
    If a `run` call succeeds but the script function (or Apps Script itself) throws an exception, the response body's error field contains this `Status` object.
    """

    code: int | None = None
    """
    The status code. For this API, this value either: - 10, indicating a `SCRIPT_TIMEOUT` error, - 3, indicating an `INVALID_ARGUMENT` error, or - 1, indicating a `CANCELLED` execution.
    """
    message: str | None = None
    """
    A developer-facing error message, which is in English. Any user-facing error message is localized and sent in the details field, or localized by the client.
    """
    details: list[dict[str, Any]] | None = None
    """
    An array that contains a single ExecutionError object that provides information about the nature of the error.
    """


class DeploymentConfig(BaseModel):
    """
    Metadata the defines how a deployment is configured.
    """

    script_id: Annotated[str | None, Field(alias='scriptId')] = None
    """
    The script project's Drive ID.
    """
    version_number: Annotated[int | None, Field(alias='versionNumber')] = None
    """
    The version number on which this deployment is based.
    """
    description: str | None = None
    """
    The description for this deployment.
    """
    manifest_file_name: Annotated[str | None, Field(alias='manifestFileName')] = None
    """
    The manifest file name for this deployment.
    """


class UpdateDeploymentRequest(BaseModel):
    """
    Request with deployment information to update an existing deployment.
    """

    deployment_config: Annotated[
        DeploymentConfig | None, Field(alias='deploymentConfig')
    ] = None
    """
    The deployment configuration.
    """


class EntryPointType(Enum):
    """
    The type of the entry point.
    """

    entry_point_type_unspecified = 'ENTRY_POINT_TYPE_UNSPECIFIED'
    web_app = 'WEB_APP'
    execution_api = 'EXECUTION_API'
    add_on = 'ADD_ON'


class AddOnType(Enum):
    """
    The add-on's required list of supported container types.
    """

    unknown_addon_type = 'UNKNOWN_ADDON_TYPE'
    gmail = 'GMAIL'
    data_studio = 'DATA_STUDIO'


class GoogleAppsScriptTypeAddOnEntryPoint(BaseModel):
    """
    An add-on entry point.
    """

    title: str | None = None
    """
    The add-on's required title.
    """
    help_url: Annotated[str | None, Field(alias='helpUrl')] = None
    """
    The add-on's optional help URL.
    """
    description: str | None = None
    """
    The add-on's optional description.
    """
    post_install_tip_url: Annotated[str | None, Field(alias='postInstallTipUrl')] = None
    """
    The add-on's required post install tip URL.
    """
    report_issue_url: Annotated[str | None, Field(alias='reportIssueUrl')] = None
    """
    The add-on's optional report issue URL.
    """
    add_on_type: Annotated[AddOnType | None, Field(alias='addOnType')] = None
    """
    The add-on's required list of supported container types.
    """


class Access(Enum):
    """
    Who has permission to run the API executable.
    """

    unknown_access = 'UNKNOWN_ACCESS'
    myself = 'MYSELF'
    domain = 'DOMAIN'
    anyone = 'ANYONE'
    anyone_anonymous = 'ANYONE_ANONYMOUS'


class GoogleAppsScriptTypeExecutionApiConfig(BaseModel):
    """
    API executable entry point configuration.
    """

    access: Access | None = None
    """
    Who has permission to run the API executable.
    """


class GoogleAppsScriptTypeExecutionApiEntryPoint(BaseModel):
    """
    An API executable entry point.
    """

    entry_point_config: Annotated[
        GoogleAppsScriptTypeExecutionApiConfig | None, Field(alias='entryPointConfig')
    ] = None
    """
    The entry point's configuration.
    """


class Access1(Enum):
    """
    Who has permission to run the web app.
    """

    unknown_access = 'UNKNOWN_ACCESS'
    myself = 'MYSELF'
    domain = 'DOMAIN'
    anyone = 'ANYONE'
    anyone_anonymous = 'ANYONE_ANONYMOUS'


class ExecuteAs(Enum):
    """
    Who to execute the web app as.
    """

    unknown_execute_as = 'UNKNOWN_EXECUTE_AS'
    user_accessing = 'USER_ACCESSING'
    user_deploying = 'USER_DEPLOYING'


class GoogleAppsScriptTypeWebAppConfig(BaseModel):
    """
    Web app entry point configuration.
    """

    access: Access1 | None = None
    """
    Who has permission to run the web app.
    """
    execute_as: Annotated[ExecuteAs | None, Field(alias='executeAs')] = None
    """
    Who to execute the web app as.
    """


class GoogleAppsScriptTypeWebAppEntryPoint(BaseModel):
    """
    A web application entry point.
    """

    url: str | None = None
    """
    The URL for the web application.
    """
    entry_point_config: Annotated[
        GoogleAppsScriptTypeWebAppConfig | None, Field(alias='entryPointConfig')
    ] = None
    """
    The entry point's configuration.
    """


class ExecutionError(BaseModel):
    """
    An object that provides information about the nature of an error resulting from an attempted execution of a script function using the Apps Script API. If a run call succeeds but the script function (or Apps Script itself) throws an exception, the response body's error field contains a Status object. The `Status` object's `details` field contains an array with a single one of these `ExecutionError` objects.
    """

    error_message: Annotated[str | None, Field(alias='errorMessage')] = None
    """
    The error message thrown by Apps Script, usually localized into the user's language.
    """
    error_type: Annotated[str | None, Field(alias='errorType')] = None
    """
    The error type, for example `TypeError` or `ReferenceError`. If the error type is unavailable, this field is not included.
    """
    script_stack_trace_elements: Annotated[
        list[ScriptStackTraceElement] | None, Field(alias='scriptStackTraceElements')
    ] = None
    """
    An array of objects that provide a stack trace through the script to show where the execution failed, with the deepest call first.
    """


class ExecutionRequest(BaseModel):
    """
    A request to run the function in a script. The script is identified by the specified `script_id`. Executing a function on a script returns results based on the implementation of the script.
    """

    session_state: Annotated[str | None, Field(alias='sessionState')] = None
    """
    *Deprecated*. For use with Android add-ons only. An ID that represents the user's current session in the Android app for Google Docs or Sheets, included as extra data in the [Intent](https://developer.android.com/guide/components/intents-filters.html) that launches the add-on. When an Android add-on is run with a session state, it gains the privileges of a [bound](https://developers.google.com/apps-script/guides/bound) script—that is, it can access information like the user's current cursor position (in Docs) or selected cell (in Sheets). To retrieve the state, call `Intent.getStringExtra("com.google.android.apps.docs.addons.SessionState")`. Optional.
    """
    function: str | None = None
    """
    The name of the function to execute in the given script. The name does not include parentheses or parameters. It can reference a function in an included library such as `Library.libFunction1`.
    """
    parameters: list[Any] | None = None
    """
    The parameters to be passed to the function being executed. The object type for each parameter should match the expected type in Apps Script. Parameters cannot be Apps Script-specific object types (such as a `Document` or a `Calendar`); they can only be primitive types such as `string`, `number`, `array`, `object`, or `boolean`. Optional.
    """
    dev_mode: Annotated[bool | None, Field(alias='devMode')] = None
    """
    If `true` and the user is an owner of the script, the script runs at the most recently saved version rather than the version deployed for use with the Apps Script API. Optional; default is `false`.
    """


class ExecutionResponse(BaseModel):
    """
    An object that provides the return value of a function executed using the Apps Script API. If the script function returns successfully, the response body's response field contains this `ExecutionResponse` object.
    """

    result: Any | None = None
    """
    The return value of the script function. The type matches the object type returned in Apps Script. Functions called using the Apps Script API cannot return Apps Script-specific objects (such as a `Document` or a `Calendar`); they can only return primitive types such as a `string`, `number`, `array`, `object`, or `boolean`.
    """


class GoogleAppsScriptTypeFunction(BaseModel):
    """
    Represents a function in a script project.
    """

    name: str | None = None
    """
    The function name in the script project.
    """
    parameters: list[str] | None = None
    """
    The ordered list of parameter names of the function in the script project.
    """


class GoogleAppsScriptTypeFunctionSet(BaseModel):
    """
    A set of functions. No duplicates are permitted.
    """

    values: list[GoogleAppsScriptTypeFunction] | None = None
    """
    A list of functions composing the set.
    """


class UserAccessLevel(Enum):
    """
    The executing users access level to the script.
    """

    user_access_level_unspecified = 'USER_ACCESS_LEVEL_UNSPECIFIED'
    none = 'NONE'
    read = 'READ'
    write = 'WRITE'
    owner = 'OWNER'


class ProcessStatus(Enum):
    """
    The executions status.
    """

    process_status_unspecified = 'PROCESS_STATUS_UNSPECIFIED'
    running = 'RUNNING'
    paused = 'PAUSED'
    completed = 'COMPLETED'
    canceled = 'CANCELED'
    failed = 'FAILED'
    timed_out = 'TIMED_OUT'
    unknown = 'UNKNOWN'
    delayed = 'DELAYED'
    execution_disabled = 'EXECUTION_DISABLED'


class ProcessType(Enum):
    """
    The executions type.
    """

    process_type_unspecified = 'PROCESS_TYPE_UNSPECIFIED'
    add_on = 'ADD_ON'
    execution_api = 'EXECUTION_API'
    time_driven = 'TIME_DRIVEN'
    trigger = 'TRIGGER'
    webapp = 'WEBAPP'
    editor = 'EDITOR'
    simple_trigger = 'SIMPLE_TRIGGER'
    menu = 'MENU'
    batch_task = 'BATCH_TASK'


class RuntimeVersion(Enum):
    """
    Which version of maestro to use to execute the script.
    """

    runtime_version_unspecified = 'RUNTIME_VERSION_UNSPECIFIED'
    deprecated_es5 = 'DEPRECATED_ES5'
    v8 = 'V8'


class GoogleAppsScriptTypeProcess(BaseModel):
    """
    Representation of a single script process execution that was started from the script editor, a trigger, an application, or using the Apps Script API. This is distinct from the `Operation` resource, which only represents executions started via the Apps Script API.
    """

    project_name: Annotated[str | None, Field(alias='projectName')] = None
    """
    Name of the script being executed.
    """
    user_access_level: Annotated[
        UserAccessLevel | None, Field(alias='userAccessLevel')
    ] = None
    """
    The executing users access level to the script.
    """
    process_status: Annotated[ProcessStatus | None, Field(alias='processStatus')] = None
    """
    The executions status.
    """
    process_type: Annotated[ProcessType | None, Field(alias='processType')] = None
    """
    The executions type.
    """
    function_name: Annotated[str | None, Field(alias='functionName')] = None
    """
    Name of the function the started the execution.
    """
    duration: str | None = None
    """
    Duration the execution spent executing.
    """
    runtime_version: Annotated[RuntimeVersion | None, Field(alias='runtimeVersion')] = (
        None
    )
    """
    Which version of maestro to use to execute the script.
    """
    start_time: Annotated[str | None, Field(alias='startTime')] = None
    """
    Time the execution started.
    """


class ListScriptProcessesResponse(BaseModel):
    """
    Response with the list of Process resources.
    """

    processes: list[GoogleAppsScriptTypeProcess] | None = None
    """
    List of processes matching request parameters.
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Token for the next page of results. If empty, there are no more pages remaining.
    """


class ListUserProcessesResponse(BaseModel):
    """
    Response with the list of Process resources.
    """

    processes: list[GoogleAppsScriptTypeProcess] | None = None
    """
    List of processes matching request parameters.
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    Token for the next page of results. If empty, there are no more pages remaining.
    """


class Type(Enum):
    """
    The type of the file.
    """

    enum_type_unspecified = 'ENUM_TYPE_UNSPECIFIED'
    server_js = 'SERVER_JS'
    html = 'HTML'
    json = 'JSON'


class File(BaseModel):
    """
    An individual file within a script project. A file is a third-party source code created by one or more developers. It can be a server-side JS code, HTML, or a configuration file. Each script project can contain multiple files.
    """

    function_set: Annotated[
        GoogleAppsScriptTypeFunctionSet | None, Field(alias='functionSet')
    ] = None
    """
    The defined set of functions in the script file, if any.
    """
    type: Type | None = None
    """
    The type of the file.
    """
    update_time: Annotated[str | None, Field(alias='updateTime')] = None
    """
    Last modified date timestamp.
    """
    name: str | None = None
    """
    The name of the file. The file extension is not part of the file name, which can be identified from the type field.
    """
    source: str | None = None
    """
    The file content.
    """
    last_modify_user: Annotated[
        GoogleAppsScriptTypeUser | None, Field(alias='lastModifyUser')
    ] = None
    """
    The user who modified the file most recently. The details visible in this object are controlled by the profile visibility settings of the last modifying user.
    """
    create_time: Annotated[str | None, Field(alias='createTime')] = None
    """
    Creation date timestamp.
    """


class Project(BaseModel):
    """
    The script project resource.
    """

    update_time: Annotated[str | None, Field(alias='updateTime')] = None
    """
    When the script was last updated.
    """
    title: str | None = None
    """
    The title for the project.
    """
    create_time: Annotated[str | None, Field(alias='createTime')] = None
    """
    When the script was created.
    """
    parent_id: Annotated[str | None, Field(alias='parentId')] = None
    """
    The parent's Drive ID that the script will be attached to. This is usually the ID of a Google Document or Google Sheet. This field is optional, and if not set, a stand-alone script will be created.
    """
    script_id: Annotated[str | None, Field(alias='scriptId')] = None
    """
    The script project's Drive ID.
    """
    creator: GoogleAppsScriptTypeUser | None = None
    """
    User who originally created the script.
    """
    last_modify_user: Annotated[
        GoogleAppsScriptTypeUser | None, Field(alias='lastModifyUser')
    ] = None
    """
    User who last modified the script.
    """


class Version(BaseModel):
    """
    A resource representing a script project version. A version is a "snapshot" of a script project and is similar to a read-only branched release. When creating deployments, the version to use must be specified.
    """

    version_number: Annotated[int | None, Field(alias='versionNumber')] = None
    """
    The incremental ID that is created by Apps Script when a version is created. This is system assigned number and is immutable once created.
    """
    description: str | None = None
    """
    The description for this version.
    """
    create_time: Annotated[str | None, Field(alias='createTime')] = None
    """
    When the version was created.
    """
    script_id: Annotated[str | None, Field(alias='scriptId')] = None
    """
    The script project's Drive ID.
    """


class Metrics(BaseModel):
    """
    Resource containing usage stats for a given script, based on the supplied filter and mask present in the request.
    """

    total_executions: Annotated[
        list[MetricsValue] | None, Field(alias='totalExecutions')
    ] = None
    """
    Number of total executions.
    """
    failed_executions: Annotated[
        list[MetricsValue] | None, Field(alias='failedExecutions')
    ] = None
    """
    Number of failed executions.
    """
    active_users: Annotated[list[MetricsValue] | None, Field(alias='activeUsers')] = (
        None
    )
    """
    Number of active users.
    """


class Operation(BaseModel):
    """
    A representation of an execution of an Apps Script function started with run. The execution response does not arrive until the function finishes executing. The maximum execution runtime is listed in the [Apps Script quotas guide](/apps-script/guides/services/quotas#current_limitations). After execution has started, it can have one of four outcomes: - If the script function returns successfully, the response field contains an ExecutionResponse object with the function's return value in the object's `result` field. - If the script function (or Apps Script itself) throws an exception, the error field contains a Status object. The `Status` object's `details` field contains an array with a single ExecutionError object that provides information about the nature of the error. - If the execution has not yet completed, the done field is `false` and the neither the `response` nor `error` fields are present. - If the `run` call itself fails (for example, because of a malformed request or an authorization error), the method returns an HTTP response code in the 4XX range with a different format for the response body. Client libraries automatically convert a 4XX response into an exception class.
    """

    done: bool | None = None
    """
    This field indicates whether the script execution has completed. A completed execution has a populated `response` field containing the ExecutionResponse from function that was executed.
    """
    error: Status | None = None
    """
    If a `run` call succeeds but the script function (or Apps Script itself) throws an exception, this field contains a Status object. The `Status` object's `details` field contains an array with a single ExecutionError object that provides information about the nature of the error.
    """
    response: dict[str, Any] | None = None
    """
    If the script function returns successfully, this field contains an ExecutionResponse object with the function's return value.
    """


class EntryPoint(BaseModel):
    """
    A configuration that defines how a deployment is accessed externally.
    """

    execution_api: Annotated[
        GoogleAppsScriptTypeExecutionApiEntryPoint | None, Field(alias='executionApi')
    ] = None
    """
    An entry point specification for Apps Script API execution calls.
    """
    entry_point_type: Annotated[
        EntryPointType | None, Field(alias='entryPointType')
    ] = None
    """
    The type of the entry point.
    """
    add_on: Annotated[
        GoogleAppsScriptTypeAddOnEntryPoint | None, Field(alias='addOn')
    ] = None
    """
    Add-on properties.
    """
    web_app: Annotated[
        GoogleAppsScriptTypeWebAppEntryPoint | None, Field(alias='webApp')
    ] = None
    """
    An entry point specification for web apps.
    """


class Content(BaseModel):
    """
    The Content resource.
    """

    script_id: Annotated[str | None, Field(alias='scriptId')] = None
    """
    The script project's Drive ID.
    """
    files: list[File] | None = None
    """
    The list of script project files. One of the files is a script manifest; it must be named "appsscript", must have type of JSON, and include the manifest configurations for the project.
    """


class ListVersionsResponse(BaseModel):
    """
    Response with the list of the versions for the specified script project.
    """

    versions: list[Version] | None = None
    """
    The list of versions.
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    The token use to fetch the next page of records. if not exist in the response, that means no more versions to list.
    """


class Deployment(BaseModel):
    """
    Representation of a single script deployment.
    """

    update_time: Annotated[str | None, Field(alias='updateTime')] = None
    """
    Last modified date time stamp.
    """
    entry_points: Annotated[list[EntryPoint] | None, Field(alias='entryPoints')] = None
    """
    The deployment's entry points.
    """
    deployment_id: Annotated[str | None, Field(alias='deploymentId')] = None
    """
    The deployment ID for this deployment.
    """
    deployment_config: Annotated[
        DeploymentConfig | None, Field(alias='deploymentConfig')
    ] = None
    """
    The deployment configuration.
    """


class ListDeploymentsResponse(BaseModel):
    """
    Response with the list of deployments for the specified Apps Script project.
    """

    deployments: list[Deployment] | None = None
    """
    The list of deployments.
    """
    next_page_token: Annotated[str | None, Field(alias='nextPageToken')] = None
    """
    The token that can be used in the next call to get the next page of results.
    """
