/**
 * Auto-generated by esbuild - DO NOT EDIT DIRECTLY
 * Source: index.js
 * Build time: 2026-03-09T13:26:21.839Z
 */

var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", { value, configurable: true });
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// src/config.js
var config_exports = {};
__export(config_exports, {
  CALENDAR_ID: () => CALENDAR_ID,
  EMAIL_QUESTION_TITLE: () => EMAIL_QUESTION_TITLE,
  EMAIL_SOURCE: () => EMAIL_SOURCE,
  SESSION_EVENTS: () => SESSION_EVENTS
});
var EMAIL_SOURCE = "question";
var EMAIL_QUESTION_TITLE = "Email";
var CALENDAR_ID = "c_ec89f4d1e8f2e6f87b6edbcbeeba3c7643c0e8b35d1ef507a58537bbee8d3785@group.calendar.google.com";
var SESSION_EVENTS = {
  "Virtual Referee Training - Session 1 (March 16, 7pm)": "79oepnm8s979rda03a5i222483@google.com",
  "Virtual Referee Training - Session 2 (March 18, 8pm)": "0gm1m5nors4u3gtnebo2giliht@google.com",
  "Virtual Referee Training - Session 3 (March 19, 8pm)": "6a1n6o0p0ii2vliqctuje8t1dv@google.com",
  "Virtual Referee Training - Session 4 (March 21, 11am)": "09fjnvbr2ap9ogqicq9ac8ramt@google.com"
};

// src/calendar.js
var calendar_exports = {};
__export(calendar_exports, {
  addGuestToSessions: () => addGuestToSessions,
  listEvents: () => listEvents
});
function addGuestToSessions(email, selectedSessions) {
  console.log("Looking up calendar:", CALENDAR_ID);
  const calendar = CalendarApp.getCalendarById(CALENDAR_ID);
  if (!calendar) {
    console.error("ABORT: Calendar not found \u2014 check CALENDAR_ID in config.js");
    return [];
  }
  console.log("Calendar found:", calendar.getName());
  const confirmed = [];
  selectedSessions.forEach((sessionName) => {
    console.log("  Matching session:", sessionName);
    const matchedKey = Object.keys(SESSION_EVENTS).find(
      (key) => sessionName.includes(key)
    );
    if (!matchedKey) {
      console.warn("  No config key matched for:", sessionName);
      return;
    }
    console.log("  Matched config key:", matchedKey);
    const eventId = SESSION_EVENTS[matchedKey];
    console.log("  Looking up event ID:", eventId);
    const event = calendar.getEventById(eventId);
    if (!event) {
      console.error("  Event not found \u2014 ID may be stale. Run listEvents() to verify. ID:", eventId);
      return;
    }
    console.log("  Event found:", event.getTitle());
    event.addGuest(email);
    confirmed.push(matchedKey);
    console.log("  Guest added:", email);
  });
  return confirmed;
}
__name(addGuestToSessions, "addGuestToSessions");
function listEvents() {
  const cal = CalendarApp.getCalendarById(CALENDAR_ID);
  cal.getEvents(/* @__PURE__ */ new Date("2026-03-01"), /* @__PURE__ */ new Date("2026-03-31")).forEach((e) => {
    console.log("TITLE:", e.getTitle(), "| ID:", e.getId());
  });
}
__name(listEvents, "listEvents");

// src/email.js
var email_exports = {};
__export(email_exports, {
  sendConfirmationEmail: () => sendConfirmationEmail
});
var BARS_LOGO_DRIVE_ID = "19v8HXXAz5a1m_rkiaUevpY0to97Q02E9";
var REPLY_TO = "rich.marzullo@bigapplerecsports.com";
function sendConfirmationEmail({ to, subject, body }) {
  if (!subject) throw new Error("sendConfirmationEmail: subject is required");
  if (!body) throw new Error("sendConfirmationEmail: body is required");
  if (!to) throw new Error("sendConfirmationEmail: to is required");
  const logoBlob = DriveApp.getFileById(BARS_LOGO_DRIVE_ID).getBlob().setName("barsLogo");
  MailApp.sendEmail({
    to,
    subject,
    htmlBody: body,
    replyTo: REPLY_TO,
    inlineImages: { barsLogo: logoBlob }
  });
}
__name(sendConfirmationEmail, "sendConfirmationEmail");

// src/trigger.js
var trigger_exports = {};
__export(trigger_exports, {
  onFormSubmit: () => onFormSubmit
});

// src/sendToLambda.js
var sendToLambda_exports = {};
__export(sendToLambda_exports, {
  sendToLambda: () => sendToLambda
});
var LAMBDA_URL = "https://tn2iit2rvsjqpqr6yhnsufefle0cfayt.lambda-url.us-east-1.on.aws/";
function sendToLambda(payload) {
  console.log("sendToLambda \u2192", JSON.stringify(payload, null, 2));
  let resp;
  try {
    resp = UrlFetchApp.fetch(LAMBDA_URL, {
      method: "post",
      contentType: "application/json",
      payload: JSON.stringify(payload),
      muteHttpExceptions: true
    });
  } catch (err) {
    console.error("sendToLambda: network error:", err.message);
    return;
  }
  console.log("sendToLambda \u2190 status:", resp.getResponseCode());
  console.log("sendToLambda \u2190 body:", resp.getContentText());
}
__name(sendToLambda, "sendToLambda");

// src/trigger.js
function onFormSubmit(e) {
  console.log("=== onFormSubmit triggered ===");
  const response = e.response;
  const allItems = response.getItemResponses();
  const errors = [];
  const rawFormResponse = {
    responseId: response.getId(),
    timestamp: response.getTimestamp().toISOString(),
    respondentEmail: response.getRespondentEmail() || null,
    items: allItems.map((r) => {
      const item = r.getItem();
      const type = item.getType().toString();
      const entry = { title: item.getTitle(), type, response: r.getResponse() };
      if (type === "CHECKBOX_GRID" || type === "GRID") {
        try {
          const g = type === "CHECKBOX_GRID" ? item.asCheckboxGridItem() : item.asGridItem();
          entry.rows = g.getRows();
          entry.columns = g.getColumns();
        } catch (_) {
        }
      }
      return entry;
    })
  };
  const firstName = allItems.find(
    (r) => r.getItem().getTitle().toLowerCase() === "first name"
  )?.getResponse()?.trim() || "";
  const lastName = allItems.find(
    (r) => r.getItem().getTitle().toLowerCase() === "last name"
  )?.getResponse()?.trim() || "";
  let email;
  if (EMAIL_SOURCE === "question") {
    const emailItem = allItems.find(
      (r) => r.getItem().getTitle().toLowerCase() === EMAIL_QUESTION_TITLE.toLowerCase()
    );
    email = emailItem ? emailItem.getResponse().trim() : "";
  } else {
    email = response.getRespondentEmail();
  }
  if (!email) {
    console.error("ABORT: No email found.");
    return;
  }
  const sessionItem = allItems.find(
    (r) => r.getItem().getTitle().toLowerCase().includes("select the virtual training session")
  );
  if (!sessionItem) {
    console.error("ABORT: Session question not found.");
    return;
  }
  const rawValue = sessionItem.getResponse();
  const selectedSessions = Array.isArray(rawValue) ? rawValue : String(rawValue).split(/,\s+(?=Virtual Referee Training)/);
  console.log("Selected sessions:", selectedSessions);
  const confirmed = addGuestToSessions(email, selectedSessions);
  console.log("Confirmed sessions:", confirmed);
  const calendarSuccess = confirmed.length === selectedSessions.length;
  if (!calendarSuccess) {
    const missed = selectedSessions.filter((s) => !confirmed.includes(s));
    errors.push(`Calendar invite failed for: ${missed.join(", ")}`);
  }
  let emailSuccess = false;
  if (confirmed.length > 0) {
    try {
      const sessionList = confirmed.map((s) => `<li>${s}</li>`).join("");
      const emailFooter = `
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 14px;">
          <p>Warmly,<br><b>BARS Leadership</b></p>
          <a href="https://www.bigapplerecsports.com" target="_blank">
            <img src="cid:barsLogo" style="width:225px; height:auto; margin-top: 15px;">
          </a>
          <p><strong>Big Apple Rec Sports</strong><br>
          Follow us: <a href="https://www.instagram.com/bigapplerecsports/">Instagram</a> | <a href="https://www.facebook.com/groups/bigapplerecsports">Facebook</a></p>
        </div>
      `;
      sendConfirmationEmail({
        to: email,
        subject: "You're registered for referee training",
        body: `
          Hi ${firstName},<br><br>
          You're confirmed for the following training session(s):<br>
          <ul>${sessionList}</ul>
          Calendar invites have been sent to you.<br><br>
          See you there!
          ${emailFooter}
        `
      });
      emailSuccess = true;
    } catch (err) {
      errors.push(`Email failed: ${err.message}`);
      console.error("Email error:", err.message);
    }
  } else {
    errors.push("No sessions confirmed \u2014 email not sent.");
    console.warn("No sessions confirmed \u2014 no email sent for:", email);
  }
  sendToLambda({
    firstName,
    lastName,
    email,
    success: calendarSuccess && emailSuccess,
    confirmedSessions: confirmed,
    selectedSessions,
    errors,
    rawFormResponse
  });
  console.log("=== onFormSubmit complete ===");
}
__name(onFormSubmit, "onFormSubmit");

// index.js
globalThis.__KIRO_MODULES__ = { config: config_exports, calendar: calendar_exports, email: email_exports, trigger: trigger_exports, sendToLambda: sendToLambda_exports };
