name: Branch Checks

on:
  push:
    branches-ignore: [ main ]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - '.github/workflows/branch-checks.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  backend-unit-tests:
    name: Backend Unit Tests (branch)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !startsWith(github.ref_name, 'dependabot/') }}
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Skip if PR is open for this branch
        id: pr-check
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`,
              state: 'open'
            });
            core.setOutput('has_open_pr', prs.data.length > 0 ? 'true' : 'false');

      - name: Set up Python 3.11
        if: steps.pr-check.outputs.has_open_pr != 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        if: steps.pr-check.outputs.has_open_pr != 'true'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        if: steps.pr-check.outputs.has_open_pr != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit and integration tests
        if: steps.pr-check.outputs.has_open_pr != 'true'
        run: |
          echo "🧪 Running unit tests..."
          python -m pytest tests/unit/ -q
          echo "🧪 Running integration tests..."
          python -m pytest tests/integration/ -q

