# .github/workflows/lambda-tests.yml
name: Lambda Tests
on:
  push:
    branches: [ main ]
    paths:
      - 'lambda-functions/**'
      - '.github/workflows/lambda-test.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run Lambda Tests
        run: |
          cd lambda-functions
          python3 tests/run_tests.py unit
